### ISSUE TITLE
Would love to figure out a way to hide canaries in list

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1000]
I know that you can do it with "--all" but these are system requests, it'd be great to figure out an alternative. Maybe an option to hide your thing from list --all? not sure

**Comment by wjam** [comment]
What about making sure labels can be specified from the command line on all jobs and then support some sort of query mechanism (include/exclude jobs with a label) - like [how Kubernetes does selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/). Then the selector has a default value of "exclude canaries"?

**Comment by aronchick** [comment]
conveniently, we have labels already :) just aren't sorting/filtering them

**Comment by simonwo** [comment]
This is done!
