### ISSUE TITLE
Have a test that runs before everything that verifies the state of test

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1008]
ETA: 2023Q1

Including:
* Can network
* Docker running
* ...

**Comment by lukemarsden** [comment]
why are the errors from the tests not sufficient? too slow?

Ideally, we make `make test` totally 100% self sufficient, only depending on golang, and then we don't need this

**Comment by lukemarsden** [comment]
related: #1029

**Comment by simonwo** [comment]
So now we have:

* `make test` runs the unit tests which are self-sufficient
* `make integration-test` runs the integration tests which are self-sufficient apart from:
    * Estuary tests contact Estuary... but only if you have an ESTUARY_API_KEY set
    * Docker tests do a check for Docker and fail fast if it isn't present

Do we think that meets the brief?
