### ISSUE TITLE
TestDockerRunSuite tests are flaky in CI

### ISSUE THREAD

**Issue by wjam** [filecoin-project/bacalhau#1018]
These tests are flaky in CI and are randomly failing. These tests are attempting parameterised tests but don't use the `t.Run` pattern to help identify which step is failing. The tests should also use a context with a timeout specified to ensure the tests don't continue for long periods of time.

* TestDockerRunSuite/TestRun_Annotations
* TestDockerRunSuite/TestRun_BadExecutables
* TestDockerRunSuite/TestRun_CreatedAt
* TestDockerRunSuite/TestRun_Deterministic_Verifier

Example: https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/1736/workflows/bd6310e8-35d1-4922-9019-129d2dbf5c78/jobs/10624

**Comment by aronchick** [comment]
Excellent find! Can you create a pattern you'd like? I'll port all these over.

**Comment by wjam** [comment]
@aronchick A pattern I've picked up from another project is to use a 'normal' timeout context with an appropriately set timeout - short enough that it doesn't needlessly hang around but long enough that you could stick a debug point in and look around for a bit.
https://github.com/filecoin-project/bacalhau/blob/131a0053a78cd2fb886461eac677e1be39c840a3/pkg/test/devstack/lotus_test.go#L41-L42

This is part of #1020

**Comment by wjam** [comment]
`TestRun_Deterministic_Verifier` was set to skip (#1045) and `TestDockerRunSuite` no longer seems flaky. Probable cause is due to hitting the package test timeout (10m)
