### ISSUE TITLE
Hard limit on concurrent jobs across the entire network

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#102]
We presently have no limit on the number or size of jobs someone could submit to the network (hello crypto miners)

I propose that we begin with a hard limit of `10` concurrent jobs across the whole network.  If you submit a new job - and the network currently has > 10 jobs in `running` state - it will reject the submitted job with a `currently busy` message.

This is a very rudamentary way of stopping spam but it quite cheap to implement so is recommended to do now rather than later

**Comment by lukemarsden** [comment]
turning off networking on the docker containers would be good as well
