### ISSUE TITLE
M1: Theme: Stabilize tests

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1020]
ETA: 2022Q4

Children:

- [x] #1264
- [x] #1030
- [x] #1032
- [x] #1033
- [x] #1034
- [x] #1035
- [x] #1036
- [x] #1064
- [x] https://github.com/filecoin-project/bacalhau/issues/410
- [x] https://github.com/filecoin-project/bacalhau/issues/471
- [x] https://github.com/filecoin-project/bacalhau/issues/519
- [x] https://github.com/filecoin-project/bacalhau/issues/523
- [x] https://github.com/filecoin-project/bacalhau/issues/812
- [x] https://github.com/filecoin-project/bacalhau/issues/635
- [x] https://github.com/filecoin-project/bacalhau/issues/1008
- [x] https://github.com/filecoin-project/bacalhau/issues/1029
- [x] https://github.com/filecoin-project/bacalhau/issues/1045
- [x] https://github.com/filecoin-project/bacalhau/issues/1080
- [x] https://github.com/filecoin-project/bacalhau/issues/1085
- [x] #382

**Comment by aronchick** [comment]
@wjam @simonwo would one of you like to own this entire thing? (not do all the work, just make sure it's getting done)

**Comment by simonwo** [comment]
Moved remaining issues to #1414.
