### ISSUE TITLE
M1 mac running (or equivalent) should be <2 min for most jobs

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1030]

**Comment by lukemarsden** [comment]
what is `time make test` saying for you now @aronchick ?

**Comment by lukemarsden** [comment]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/264658/202182137-2f0f609a-b446-4944-b0f0-fb7d0bd677ce.png">

```
luke@chunky:~/pb/bacalhau$ time go test ./... -v -count 1
real	1m4.993s
user	1m8.575s
sys	0m11.938s
```

at just over one minute, calling this done :) assuming we are happy to rely on CI for integration tests

**Comment by lukemarsden** [comment]
as a followup to this, the lotus tests don't seem super happy on M1 Mac. So, let's just say we let CI run those for us.

**Comment by lukemarsden** [comment]
similarly, pyodide runs with amd64 emulation, so is likely also to be not great on M1 Mac
