### ISSUE TITLE
Remove all logging information during test runs and/or devstack

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1032]
ETA: 2022Q4

When running locally, the logs are virtually unusable. Just a wall of meaningless text. Need to improve.

Further, we do a lot of OpenTelemetry stuff - we should detect and turn that off (with no errors) when running DevStack.

**Comment by lukemarsden** [comment]
I don't find the logging too hard to interpret, can you give some specific examples of things that we should change please?

**Comment by simonwo** [comment]
@aronchick What would improve this for you? The logging seems to be useful in debugging situations, but I agree there is a lot of it. Would you prefer logs to only be shown if tests fail?

**Comment by simonwo** [comment]
I'm closing this as I don't think we've reached a consensus on whether a change is required. Please re-open with more details if necessary!
