### ISSUE TITLE
Implement parallel?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1034]
ETA: 2022Q4

Go test suites offer built in parallelization - we should do our best to use.

**Comment by lukemarsden** [comment]
`make test` implicitly uses parallelism, see the "BUT" part of this answer: https://stackoverflow.com/a/58987438
`make integration-test` has `-p 1` for now still, since I've seen flakiness with parallelised integration tests

**Comment by wjam** [comment]
Remember that Go offers _two_ types of parallel when running tests -`-p` for running multiple test _packages_ at the same time and `-parallel` for running multiple _tests_ at the same time. I presume this is about using the `-p` flag?
