### ISSUE TITLE
Need to support Testing when offline

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#104]
=> ERROR [internal] load metadata for docker.io/library/ubuntu:20.04                                                                            0.0s
------
 > [internal] load metadata for docker.io/library/ubuntu:20.04:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/ubuntu/manifests/20.04": Service Unavailable
make: *** [build-ipfs-sidecar-image] Error 1

**Comment by lukemarsden** [comment]
why?

**Comment by aronchick** [comment]
To support people who want to dev when on a plane/train/shoddy wifi, speed tests, etc

**Comment by aronchick** [comment]
think this is closed?
