### ISSUE TITLE
Create template for design docs

### ISSUE THREAD

**Issue by wdbaruni** [filecoin-project/bacalhau#1075]
Create a template to help writing future design docs. The goal is not to enforce the template, but just to be a good starting point and to highlight the important sections and content most design docs should cover

**Comment by lukemarsden** [comment]
we have one of these in Google docs already that Vedant made based on my suggestions. let's move it over to notion and link to clearly from a central notion index page

**Comment by wdbaruni** [comment]
This is the only one I found in Google docs https://docs.google.com/document/d/10ifdDbFcIsUFQPgAqxjHiMOJ37HlS7hvrKK0wHS9Vus

My goal is to create a richer template with more guidance. Unless there is another template I couldn't find, there is still some work needed here

**Comment by lukemarsden** [comment]
Yup that's the one, design away!

**Comment by ricmk** [comment]
I wrote up a standard Design doc template (in the shape of a Design doc) based on my experience in web2 the last 10+ years. I also presented a brief talk about what a design doc is and what benefits it provides [slide deck here](https://docs.google.com/presentation/d/1gYNegzs1uLW8mGfeY9hPpWlabEvTgXkK7Aj0bYcERgc/edit#slide=id.gc6f73a04f_0_0)

**Comment by ricmk** [comment]
[Design Doc Template is here](https://www.notion.so/pl-strflt/Writing-a-Design-Doc-aa6034be43c2434ba88a2fd844516e94)
