### ISSUE TITLE
run linux arm64 tests

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#1085]
ETA: 2023Q1

No reason not to run our tests on Linux ARM64. They are currently disabled in the CircleCI config

**Comment by lukemarsden** [comment]
Equally we should run the macOS arm64 tests! Not least because of the prevalence of macOS ARM developers these days.

**Comment by wjam** [comment]
We aren't running tests on ARM architectures because we aren't _running_ on ARM architectures - we are running on amd64 machines but creating arm64 binaries

**Comment by wjam** [comment]
#1267 and #1268 raised for tests that had to be skipped as they didn't work on Linux arm64
