### ISSUE TITLE
Bacalhau Run Failure: "unsupported protocol scheme"

### ISSUE THREAD

**Issue by wesfloyd** [filecoin-project/bacalhau#112]
To reproduce: install the bacalhau CLI and run the first example "bacalhau run" command [per the documentation](https://docs.bacalhau.org/getting-started/installation)

Expected result: bacalhau CLI submits the job to the production network

Actual result: job submission fails with error "unsupported protocol scheme"

Potential solutions: appending "http://..."  to the URL [in root.go](https://github.com/filecoin-project/bacalhau/blob/b83f1fae9b29ed6c9c0ad446761f9d946943c174/cmd/bacalhau/root.go#L19)

![image](https://user-images.githubusercontent.com/260568/171900264-1ab92d22-34e4-496c-a02f-905e02b11a45.png)

**Comment by aronchick** [comment]
Ok, fixed the bug (missing protocol on the golang) but the response from the server is not working, and we're not doing any meaningful logging/catching of the error. Should probably try to fix that :) 

cc @lukemarsden @binocarlos

**Comment by lukemarsden** [comment]
The response from the server is not working because we have not upgraded
production to REST yet (from JSONRPC). We should have coordinated releasing
the CLI and upgrading production at the same time around the protocol
change.

I'll upgrade and test production on Monday.
