### ISSUE TITLE
M3: Dockerize Bacalhau

### ISSUE THREAD

**Issue by wdbaruni** [filecoin-project/bacalhau#1120]
Deploying Bacalhau to production is more than just running a binary. We have dependencies that must be installed and running on the servers, including IPFS, Prometheus, log publishing agent (missing today), health checker, Postgres client, ...

Node preparation complexity is visible in [install_node.sh](https://github.com/filecoin-project/bacalhau/blob/b2120012ea/ops/terraform/remote_files/scripts/install-node.sh) and #802

This task is about exploring shipping Bacalhau as a docker image along with all the mentioned dependencies. This is part of #1119 as it can open the door to run Bacalhau on ECS, which can also simplify periodic benchmarking of the network by adding hundreds or thousands of nodes on fewer machines

ETA: 2023Q2

**Comment by aronchick** [comment]
Fascinating! What if we went the other direction? Would it be possible to pack all dependencies into a single binary?

**Comment by philwinder** [comment]
@wdbaruni Just had a chat on slack: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1669280791045329

And cc this PR: https://github.com/filecoin-project/bacalhau/pull/1364

Tasks:

* [ ] Develop Bacalhau docker container (see #1364)
* [ ] Add CI to build images for all systems
* [ ] Add instructions to compute provider docs and refactor a bit to show the different installation methods
* [ ] Add to the user docs to show people how to run a private node for testing purposes

**Comment by SvenDowideit** [comment]
oh boy, yup, I'll go read the install_node.sh etc, and work on #1364 to add that to both the quickstart Docker image, and some words for users that want to setup a node manually

**Comment by philwinder** [comment]
Added to docs: https://github.com/bacalhau-project/docs.bacalhau.org/pull/81

A bit rough, and a few edge cases, but mostly working.
