### ISSUE TITLE
Failed jobs aren't marked as failed in CircleCI

### ISSUE THREAD

**Issue by wjam** [filecoin-project/bacalhau#1125]
https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/1910/workflows/cf1b8026-eb09-4094-97a3-a4f82673199a/jobs/12320

The job above has failed tests yet isn't marked as failed (build-windows-amd64-unit-1).

**Comment by simonwo** [comment]
Fixed in https://github.com/filecoin-project/bacalhau/commit/92bb62e85a8fdc37602d1e43f7856af02d1b1093.
