### ISSUE TITLE
Need a way to simulate as close to running in the cloud but locally

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#113]
Ideas:

- [ ] bacalhau run local_python_script.py --local # Mounts in a file from local into a python container that we provide
- [ ] bacalhau run local_python_script.py --requirements=requirements.txt --local # Should probably also support RStudio
- [ ] bacalhau run python-3.7-container  local_python_script.py --local # Mounts the python script into an arbitrary container at a pre-defined mount point
- [ ] bacalhau run python-3.7-container  local_python_script.py --local --debug # This is some crazy thoughts, but is there something we could do to make debugging in VSCode easier? And/or set LOG_LEVEL=debug in the container? Or something OTel related?

**Comment by aronchick** [comment]
cc @Bubblyworld

**Comment by aronchick** [comment]
cc @js-ts - some more details in the past. feel free to close as dupe

**Comment by js-ts** [comment]
Moved to https://github.com/filecoin-project/bacalhau/issues/105
