### ISSUE TITLE
Download using Estuary API for results published to Estuary

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1138]

**Comment by pyropy** [comment]
Currently job publisher starts publishing it's job result concurrently to both IPFS and Estuary. 
Given that publisher publishes data to local IPFS node its usually faster then upload to Estuary, causing only IPFS result (CID) to be returned as job result. 

Possible improvement is for publisher would to wait for few seconds before returning job results to ensure that there's a bigger chance for Estuary publisher to finish the publish process.

In case Estuary publisher finishes in time, URL for Estuary download should be added to return [value](https://github.com/filecoin-project/bacalhau/blob/7a107b35f5ad80eb34c48018b60fe2a0fa0ce339/pkg/publisher/estuary/publisher.go#L94).

Bacalhau CLI `get` command should also be changed to download from Estuary when possible and fallback to IPFS if there is no results for Estuary.

**Comment by pyropy** [comment]
@simonwo I guess we can close this issue?

**Comment by simonwo** [comment]
Yes! Merged in #1527.
