### ISSUE TITLE
Implement centralized logging to easy log management, unified data collection. and facilitate bug hunting

### ISSUE THREAD

**Issue by wdbaruni** [filecoin-project/bacalhau#1149]
ETA: 2022Q4

Onboard with a logging service to store and query logs

**Comment by lukemarsden** [comment]
Can we just ship journalctl logs into GCP logging service?

**Comment by enricorotundo** [comment]
we could use Loki for this, it's a Grafana tool

**Comment by enricorotundo** [comment]
Loki dashboard for aggregated logs (requires credentials): https://protocollabs.grafana.net/goto/lKmGkWT4z?orgId=1

**Comment by enricorotundo** [comment]
Implemented in https://github.com/filecoin-project/bacalhau/pull/1662
Closing this one :)
