### ISSUE TITLE
Error Using parentheses in -fx operator in magick

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#115]
https://imagemagick.org/script/fx.php
Using the -fx image operator in magick requires providing with an equation which requires use of parentheses ()
in many cases but the same job works without use of paranthesis but this isn't the case for every other job

<img width="757" alt="image" src="https://user-images.githubusercontent.com/79689323/172486052-ede19e15-c3c6-4489-a797-3fc19d2655bf.png">
COMMAND

`bacalhau run \
  -v QmeZRGhe4PmjctYVSVHuEiA9oSXnqmYa4kQubSHgWbjv72:/input_images \
  -o results:/output_images \
  dpokidov/imagemagick \
  -- magick mogrify -fx "((g-b)/(r+g+b))>0.02 ? 1 : 0" -quality 100 -path /output_images /input_images/*.jpg`

<img width="597" alt="image" src="https://user-images.githubusercontent.com/79689323/172487245-c488998c-4943-44ec-ab3e-cb8f95e2f858.png">

`bacalhau run \
 -v QmeZRGhe4PmjctYVSVHuEiA9oSXnqmYa4kQubSHgWbjv72:/input_images \
 -o results:/output_images \
 dpokidov/imagemagick \
 -- magick mogrify -fx "g-b/r+g+b>0.02 ? 1 : 0" -quality 100 -path /output_images /input_images/*.jpg`

**Comment by aronchick** [comment]
can you try the same, but using single quotes instead of double quotes? e.g. ' instead of "

**Comment by js-ts** [comment]
<img width="760" alt="image" src="https://user-images.githubusercontent.com/79689323/172533221-fe5bf8a5-8426-4493-9b61-709900bbdd7d.png">

`
bacalhau run \
  -v QmeZRGhe4PmjctYVSVHuEiA9oSXnqmYa4kQubSHgWbjv72:/input_images \
  -o results:/output_images \
  dpokidov/imagemagick \
  -- magick mogrify -fx '((g-b)/(r+g+b))>0.02 ? 1 : 0' -resize 256x256 -quality 100 -path /output_images /input_images/*.jpg
`

**Comment by aronchick** [comment]
does this work against a standard docker container? I can get it to work but it doesn't right now
