### ISSUE TITLE
12. Results aggregation

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#12]
- [x] Client considers results from everywhere
- [x] More than one miner has run the job, present summary of multiple results
- [x] Jobs are aggregated and evaluated
- [x] Confidence score system in the client: filtering aggregated results step like `kubectl –wait`
- [x] Deliverable: two compute nodes do the same job and the client is able to display status on both

**Comment by lukemarsden** [comment]
We're going to compare traces rather than outputs for evaluation. By getting a human to do it to begin with! (maybe with a cute little frontend)
