### ISSUE TITLE
API endpoints take all parameters in a single (required) payload

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#1207]
This approach doesn't really allow us to express what the optional parameters are.

**Comment by enricorotundo** [comment]
⚠️ Disclaimer: this may be just me nitpicking around how we make HTTP requests 😸 

To add more context to this issue 👇 

This is where we're standing at the moment. Every endpoint follows the approach below.
We accept only one single object in the request `body` where we expect a number of fields. To keep this simple, let's ignore the nested documents for now. The top-level attributes (e.g. `client_public_key`, `signature`, `data`) are part of a single flat body. 

<img width="919" alt="Screenshot 2022-11-18 at 10 16 48" src="https://user-images.githubusercontent.com/4340327/202666091-9dffe05f-b46c-4f23-b029-617c985c64c4.png">


That highlights (some) endpoints could instead make a better use of HTTP expressivity and employ parameters such as [query, url, etc](https://swagger.io/docs/specification/describing-parameters/#path-parameters). This way, `/list` would use a path (ie. `/list/{job-id}`) to return info about a specific job, instead of expecting a body like `{..., "id":"<a-job-id>", ....}`.
For example, see below how the Estuary API exposes separate parameters. This makes documenting them every easier/nicer!

<img width="782" alt="Screenshot 2022-11-18 at 10 14 27" src="https://user-images.githubusercontent.com/4340327/202665610-608383ad-dd0f-4402-8e83-1053fe075178.png">

**Comment by philwinder** [comment]
Will be tackled in #1199. Also see notion for current thoughts.
