### ISSUE TITLE
Arbitrary networking via gateway.

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1245]
ETA: 2023Q3

**Comment by wesfloyd** [comment]
Workloads that can benefit once this feature is implemented:
- Filecoin Green REC
- Impact Evaluators with Ceramic
- LabDAO Lab Exchange


Workloads that are blocked until this feature is implemented:
- Internal PL Snapshot team: Filecoin Chain Archiver
- Internal PL Data team: Lily Sentinel Analytics
- University of Cambridge Cell Modeller
- Pangeo Forge for Ocean Weather and Climate Science
- True Blocks EVM Snapshotting

Sourced from [workloads tab here](https://airtable.com/invite/l?inviteId=invrPIDm8Lff7F4JJ&inviteToken=69496b2e9bbb2da64689e6ae193e5189dca71a4defdeb0d28e1de6505b404339&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts)

**Comment by wesfloyd** [comment]
I've just sent notifications to the workload owners listed above to invite them to use the new networking feature:

https://docs.bacalhau.org/next-steps/networking/

**Comment by aronchick** [comment]
is this done @simonwo ?
