### ISSUE TITLE
Remove --allow-empty flag from Swagger build in CI

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#1487]
Otherwise the git history gets very noisy e.g. https://github.com/filecoin-project/bacalhau/releases/tag/v0.3.14

**Comment by simonwo** [comment]
This might have been fixed by 522d48728644a6e5274ed92189abc21b2fa1ce8a?

**Comment by enricorotundo** [comment]
Assigned to Simon for the kudos
