### ISSUE TITLE
16. Do research into payment, incentives and rewards, meet and discuss with experts, and make some recommendations for future work

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#15]
- [x] Deliverable: meetings with Protocol Labs experts in proof of spacetime, written conclusions on how we can adapt this or other algorithms to provide a payment layer for Bacalhau

**Comment by wesfloyd** [comment]
Have you guys considered allowing the payments (compute lease) to be negotiated/mediated by an EVM smart contract (e.g. arbitrum, polygon, etc.)? That would allow for:

1. Up front commitments by the entity submitting the job to the duration of compute
2. Payments on demand at any convenient time interval while the long running jobs are operating correctly (e.g. every minute or hour)
3. Termination and return of funds to the entity who submitted the job in case they are unsatisfied with the service provided
4. Flexible, competitive market pricing dynamics as a result of modern smart contract pool architectures (e.g. the designs used by AMM DEXs)
