### ISSUE TITLE
17. Research possibility of partial verification to reduce energy usage and cost

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#16]
- [x] Sharding 100 shards of data I only need 3% of them to be verified
- [x] And how miners would be penalised for lying
- [x] This might relate to proof of space-time
- [x] Deliverable: meetings with Protocol Labs experts in proof of spacetime, written conclusions on how we can approach confidence when not every job has been run multiple times

**Comment by wesfloyd** [comment]
Is the purpose of the project to support long running general compute jobs (e.g. backend API serving, container/kubernetes workloads)? Or is it primarily to support Filecoin compute services?
