### ISSUE TITLE
Allow changing the format of `bacalhau describe` to JSON or YAML

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#1607]
We have a command `bacalhau describe` that outputs the spec and status of a job. This command currently prints the spec in YAML format.

Our messaging actually serialises to JSON, which is generally regarded as a safer and easier data format to work with. We should support a flag to `describe` like `--json` to output only in JSON format.

**Comment by KalindaC-muSpace** [comment]
Hello, I would like to contribute by solving this issue. Could you provide background describing the case and some directions (it is my first time working on an open-source project)? Thanks!

**Comment by KalindaC-muSpace** [comment]
@aronchick @simonwo Please help :)

**Comment by simonwo** [comment]
Hi @KalindaC-muSpace! 👋 I've added some comments to the description. 

Start by cloning the repository and making sure you can run the code locally by e.g. running `go run . docker run ubuntu date` followed by `go run . describe`. Then have a look in `cmd/bacalhau/describe.go` for how the describe command works. 

You can see that it already accepts some flags, to which you'll need to add a `--json` flag: https://github.com/filecoin-project/bacalhau/blob/72c15eb626c80f5d57447f5519043f76787f99fd/cmd/bacalhau/describe.go#L61-L64

And then in fact it already parses to JSON but converts that to YAML, so when the `--json` flag is set you only need to skip that last step! https://github.com/filecoin-project/bacalhau/blob/72c15eb626c80f5d57447f5519043f76787f99fd/cmd/bacalhau/describe.go#L139-L143

Let me know if you have any questions or concerns :)

**Comment by KalindaC-muSpace** [comment]
This was very helpful, I'll get to work on it right away.
