### ISSUE TITLE
Missing jq in local test

### ISSUE THREAD

**Issue by olgibbons** [filecoin-project/bacalhau#1772]
The TestNetworkAllowlistStrategy test was failing because I didn't have jq installed locally. Is there a dependency file that I can update?

**Comment by simonwo** [comment]
We don't have a dependency file for binary packages... as how you install is different across Ubuntu, Mac OS X or Windows.

Probably the thing to do is put a check in the Makefile for `jq` (by running `which jq`) and print an error message if it's not found, so at least people know what is missing. Something like: https://github.com/filecoin-project/bacalhau/blob/f668fe9e9e254371b937a5c94c4b51690ef943e1/Makefile#L96-L100
