### ISSUE TITLE
21. Encryption between clients and compute nodes to avoid snooping [was Placeholder milestone 2]

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#19]
- [ ] FINAL DELIVERABLE: xxx (@lukemarsden to fill in)

**Comment by aronchick** [comment]
cc @binocarlos - isn't this done? don't we already go over ssl?

**Comment by lukemarsden** [comment]
No, we don't, and this isn't done. It will be done as part of the hash
based verifier
