### ISSUE TITLE
Bacalhau docker run does not respect docker image updates

### ISSUE THREAD

**Issue by jsolly** [filecoin-project/bacalhau#1982]
## Context 
If you run a docker image on Bacalhau, update the image, and then try to run it again, Bacalhau does not use the latest image.

## Steps to Reproduce 
Create a basic dockerfile that echos something
```dockerfle
FROM ubuntu
CMD echo "Hello World!"
# CMD echo "¡Hola Mundo!"
```
Now build the image and push to DockerHub
```shell
$ docker login
$ docker build -t <username>/<image_name>:tag .
$ docker run <username>/<image_name>:tag
> Hello World!
$ docker push <username>/<image_name>:tag
```
Now run the image on Bacalhau
```shell
$ bacalhau docker run <username>/<image_name>:tag
$ bacalhau describe <job_id>
 > stdout: |
         Hello World!
```
Now uncomment the line echoing Hello World in Spanish and rebuild + push image using the same name and tag
```shell
$ docker build -t <username>/<image_name>:tag .
$ docker run <username>/<image_name>:tag
> ¡Hola Mundo!
$ docker push <username>/<image_name>:tag
```
Now try to run the image again in Bacalhau
```shell
$ bacalhau docker run <username>/<image_name>:tag
$ bacalhau describe <job_id>
 > stdout: |
         Hello World!
```
Bacalhau continues to echo Hello World even though the image has changed.

## Expected Behavior 
Bacalhau always uses the latest image from DockerHub.

## Thoughts
Is this expected behavior? I think it could get really confusing if Bacalhau only remembers the first version of an image it runs. 

I can also reproduce this using no tag (latest). Docker only seems to remember the first time the image is run. After that first run, Bacalhal does not seem to recognize any updates to the image on dockerhub.

My guess is that Bacalhau is caching the image and not invalidating the cache if the image digest has changed on DockerHub.

## Workaround
Whenever you make an update to an image, always use a new tag or name.

## Environment
Client Version: v0.3.19
Server Version: v0.3.19

**Comment by aronchick** [comment]
SOOOO i think you will find this is actually the docker daemon. The issue is that docker will not redownload an image if the tag is the same as the one it's already downloaded.

We actually had a bug to warn the user that we were using a cache - https://github.com/filecoin-project/bacalhau/issues/1603

I wonder if there's a better way?

**Comment by aronchick** [comment]
BTW, the reason your thing works is because you've actually cached the new tag with the new build. if you set up two environments side by side, and execute in the other one, you'll note that it doesn't pull the cache.

**Comment by jsolly** [comment]
Got it. That makes sense if I am using a tag, but what about when I am not using a tag?

I see when I run an image without a tag I get a message as implemented in https://github.com/filecoin-project/bacalhau/pull/1763
```shell
$ bacalhau docker run <username>/<image_name>
> Using default tag: latest. Please specify a tag/digest for better reproducibility.
```

I think I am a bit confused on how https://github.com/filecoin-project/bacalhau/issues/1603 was resolved. According to my testing, no-tag images ARE cached and NOT refreshed when updated. When I update a tag-less image and run it in Bacalhau, it never runs the latest image. The image is always set to whatever it was when it was first run.

If Bacalhau is using the default tag: latest, I would assume it is using the latest, but it's not.

I would argue that https://github.com/filecoin-project/bacalhau/pull/1763 does not fix https://github.com/filecoin-project/bacalhau/issues/1603.

**Comment by jsolly** [comment]
Not sure any message within the CLI would be sufficient. Perhaps find a way to work this into the docs. Thanks for your help. Closing this one now.

**Comment by aronchick** [comment]
Yeah, i'm really sorry about this @jsolly - it's just what we've been given with Docker. It IS interesting, what if we blocked on NOT using a tag? Or asked for an extra flag if not?

**Comment by jsolly** [comment]
No, I don't think blocking is a good idea. The lower barrier to entry, the better...and most people don't appreciate being corraled like that.

I think a FAQ that covers common 'gotchas' might be nice, but this was purely a user error on my part for not understanding how Docker works.
