### ISSUE TITLE
Much improved logging library

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#226]
To augment otel that keeps track of events as well as text output so we can get a JSON log of what node did what with what job (to make debugging easier)

**Comment by aronchick** [comment]
we already have zerolog included - all we have to do is export it with the default writer.

**Comment by binocarlos** [comment]
> we already have zerolog included - all we have to do is export it with the default writer.

:+1: 

The "improvement" part here is there is now a "job event" logger which cuts out all the other noise.

Nothing has changed about the existing logging library (other than there is a env variable to control which writer we use text or json)

The addition is there is now a "jobevent" logging type which hides all the other log events and only shows the key state transition events to make debugging a single job a bit easier.

I think I was being over zelous when I called this issue "much improved" :smile:
