### ISSUE TITLE
Ops: set up monitoring and alerting of production being down, and CPU/mem/disk usages

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#229]
So that we have a basic handle on the health of our production nodes (at least the ones we're running).

Prometheus + Grafana would be a natural choice for the CPU/mem/disk usage and alerting on those. With alertmanager plugged into Slack.

Something external like Pingdom with Slack alerts would be fine for our CLI REST endpoint.

**Comment by aronchick** [comment]
Id like to pick this up - qq on the monitoring, do you envision having Prometheus set up per node? Or do you want us scraping public metrics? (Eg do we public the metrics to a url that can be scraped)

**Comment by lukemarsden** [comment]
Prometheus node exporter definitely for system level metrics (CPU/mem/disk)

And endpoints on the nodes is great too

We might wanna use grafana cloud to begin with for simplicity

And instrument bacalhau with Prometheus for app level metrics like time
spent waiting and number of jobs processed etc

**Comment by enricorotundo** [comment]
Note: I've recently added Prometheus

**Comment by enricorotundo** [comment]
@lukemarsden @wdbaruni Are we happy with the Canary or would like alerting from app metrics too? The Canary has proven to bee quite good at its job already!
