### ISSUE TITLE
7. Job execution investigation: wasm

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#23]
- [ ] Build a prototype of wasm execution backend
- [ ] Deliverable: a job can start a wasm process and execute some arbitrary python code provided by the user (for example)

**Comment by wesfloyd** [comment]
Adding an interesting WASM runtime. Apparently this is the one [FVM will be using](https://github.com/filecoin-project/fvm-specs/blob/main/03-impl-notes.md):
[Wasmer](https://docs.wasmer.io/ecosystem/wasmer)
