### ISSUE TITLE
Hello World Example Failing: "Error: unknown flag: --sort-by"

### ISSUE THREAD

**Issue by wesfloyd** [filecoin-project/bacalhau#243]
Steps to reproduce: install and [run the hello world example](https://docs.bacalhau.org/getting-started/installation).

Expected result: Output of command `bacalhau list --wide --sort-by=id --id-filter=<JOB_ID>` yields a filtered list of jobs

Actual result: command fails with two separate flag errors "Error: unknown flag: --sort-by" and then "Error: unknown flag: --id-filter" once the first flag is removed.

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/260568/173356163-742ad4ce-c596-4ed0-9241-dc9ab234c974.png">

<img width="1399" alt="image" src="https://user-images.githubusercontent.com/260568/173356328-50da448e-914f-42f8-8f78-452f0157c081.png">

**Comment by wesfloyd** [comment]
Just realizing I mistakenly ran this command from within my Bacalhau build folder (palm_to_face). Closing as "Not an Issue"

**Comment by wesfloyd** [comment]
"Not an Issue"

**Comment by aronchick** [comment]
just fyi, this won't work until we cut a new release - fyi @lukemarsden

**Comment by wesfloyd** [comment]
Reopening as this behavior just appeared for me again with a fresh test on v0.1.8

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/260568/173712072-f7de0f89-674f-4a4d-b34b-400262ad9b78.png">

**Comment by aronchick** [comment]
Still not repro able from main
