### ISSUE TITLE
Bacalhau Install Fails on Mac

### ISSUE THREAD

**Issue by wesfloyd** [filecoin-project/bacalhau#245]
Steps to reproduce: follow installation instructions to [install the CLI on Mac OS](https://docs.bacalhau.org/getting-started/installation)

Expected result: bacalhau CLI is installed correctly

Actual results:
- error shown "bash: line 212: 13659 Killed: 9               $BACALHAU_CLI_FILE --version"
- Bacalhau CLI does not execute

<img width="1421" alt="image" src="https://user-images.githubusercontent.com/260568/173357392-264a231e-4358-400d-af86-b5474f7a13a7.png">

<img width="423" alt="image" src="https://user-images.githubusercontent.com/260568/173357622-6673c16b-633f-4a88-9bb5-4e3a4ebcac7a.png">

**Comment by wesfloyd** [comment]
Note - the install appears to work correctly on Ubuntu.latest

**Comment by aronchick** [comment]
this is because you already have one installed under rosetta (or vice versa). Please remove the app first.

**Comment by aronchick** [comment]
Can't repro
