### ISSUE TITLE
We need to rename this - what does it mean to be "furthest along" for a job? Closest to final?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#259]
```
// TODO: We need to rename this - what does it mean to be "furthest along" for a job? Closest to final?
```

https://github.com/filecoin-project/bacalhau/blob/bf4da6850444d4f312bb2186d8943c32d0036702/pkg/job/job.go#L111

**Comment by aronchick** [comment]
Still valid? Is this another state machine? 

cc @wdbaruni

**Comment by wdbaruni** [comment]
I don't see the TODO statement any more. Assuming it has been addressed and will close the issue
