### ISSUE TITLE
Hate to bring this up again, but this is looking like leaking again - non-deterministically failing test in this test.

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#261]
```
// TODO: Hate to bring this up again, but this is looking like leaking again - non-deterministically failing test in this test.
```

https://github.com/filecoin-project/bacalhau/blob/471cb01f8030b15607de31fc375ba7562735c487/cmd/bacalhau/run_test.go#L114

**Comment by Bubblyworld** [comment]
Yep, we weren't shutting down `APIServer` instances after they start listening, which was eating file descriptors. Am busy fixing now.

**Comment by Bubblyworld** [comment]
<img width="877" alt="Screenshot 2022-06-19 at 11 29 33" src="https://user-images.githubusercontent.com/6214591/174474552-93ee2fc6-c97d-4a03-b5a6-640305f52095.png">

Okay, that solves the file descriptor issue, but this one looks like the test isn't waiting for a request to complete before checking the results. I'm guessing the CLI returns after submitting the job, but there's still a delay before the server processes it.

**Comment by Bubblyworld** [comment]
<img width="1238" alt="Screenshot 2022-06-19 at 11 39 03" src="https://user-images.githubusercontent.com/6214591/174474868-49437de5-b95e-469f-90d8-a636157617a3.png">
Mmm, actually it appears to be an error in the test code - `ExecuteCobraCommand` isn't returning a job ID, so we're just calling `c.Get(...)` with an empty string. Which should be erroring, but it appears to return a random job?

**Comment by Bubblyworld** [comment]
<img width="1242" alt="Screenshot 2022-06-19 at 11 43 24" src="https://user-images.githubusercontent.com/6214591/174475120-74184871-5021-43b7-af75-46c5a7944200.png">
Yep, that's the cause. Sometimes you get lucky and the randomly returned job just _happens_ to be the one you wanted, which is why the test is nondeterministic.

**Comment by Bubblyworld** [comment]
Okay, fixes for everything have been pushed to the `describe` branch.

**Comment by aronchick** [comment]
LOL, amazing find. OMG, that would have pulled my hair out.
