### ISSUE TITLE
Move terraform state files for production and any other environments to GCS

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#272]
https://cloud.google.com/docs/terraform/resource-management/store-state

This will allow more than one person to make changes to the production (and any other) infrastructure without needing to manually pass tfstate files around.

**Comment by lukemarsden** [comment]
already done in https://github.com/filecoin-project/bacalhau/commit/8b039ac8fddf98961ff0676552d67406ae07227a - thanks @aronchick !

Next step is to manually migrate the state files we've been using locally for production to that bucket. Or just blow away production and start again but then we'd have to change our production hashes.

**Comment by binocarlos** [comment]
This is all done now with: https://github.com/filecoin-project/bacalhau/pull/335

You can [read here](https://github.com/filecoin-project/bacalhau/tree/main/ops) how to use workspaces in our bucket
