### ISSUE TITLE
support for :ro readonly input volumes

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#279]
docker command:

```
docker run -ti --rm \
    -v /Users/srycajal/data/ds005:/bids_dataset:ro \
    -v /Users/srycajal/outputs:/outputs \
    bids/example:0.0.4 \
    /bids_dataset /outputs participant --participant_label 01
```
bacalhau command:
`bacalhau run     -v QmdnMxSSvD8QYR6F4S7wkgQsW16bR6U7zyDTbiEm72RPpB:/bids_dataset:ro     -v /outputs:/outputs     -o /outputs:/outputs --skip-syntax-checking     bids/example:0.0.4 -- /bids_dataset /outputs participant --participant_label 01`
error:
![image](https://user-images.githubusercontent.com/79689323/175570171-e022296c-fb28-4a48-a9dc-7ad5e2370a00.png)

**Comment by aronchick** [comment]
Heya - can you help me understand why you'd need this? all mounts should be read only no matter what - it's IPFS :)
