### ISSUE TITLE
we need these to avoid stream based deadlocks

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#282]
```
// TODO: we need these to avoid stream based deadlocks
```

https://github.com/filecoin-project/bacalhau/blob/d3d8d4c63aed955517ad0e40b0fc039875220291/pkg/system/utils.go#L16

**Comment by lukemarsden** [comment]
Why is this an issue? This is just how the code works

**Comment by aronchick** [comment]
I didn't enter the comment. Someone else did, but they didn't enter it in GitHub.
