### ISSUE TITLE
--output json not showing the json for a particular job

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#284]
If a user wants the output json a particular job it shouldnt give outout json for all jobs, very long to search it manually
 bacalhau list --sort-by=id --reverse --id-filter=c47de041 --wide --output json

https://gist.github.com/js-ts/66d257005d4fc4fc8633cc213aec73cf

<img width="668" alt="image" src="https://user-images.githubusercontent.com/79689323/175957131-02c1ef40-f0e1-4778-8e24-ba8f6ef498da.png">

**Comment by aronchick** [comment]
Can you confirm if this is still true @js-ts ? May have fixed it

**Comment by js-ts** [comment]
this is not fixed in Bacalhau Version: v0.1.16, but would it be fixed in later versions ?

**Comment by aronchick** [comment]
i'll check
