### ISSUE TITLE
Fix if when we care about optimization of memory (224 bytes copied)

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#287]
```
	// TODO: Fix if when we care about optimization of memory (224 bytes copied)
```

https://github.com/filecoin-project/bacalhau/blob/fba8654baa6fbd9daa9b7df838c8adc138c06536/pkg/executor/docker/executor.go#L309

**Comment by wjam** [comment]
I removed the `nolint` comment from that line and linting didn't complain about anything. It's possible that the line at issue was this?

https://github.com/filecoin-project/bacalhau/blob/17d00d91b61661f0ce74bb6030f271633dfb3b0d/pkg/docker/utils.go#L77
