### ISSUE TITLE
we need to work out how to upload a tar file

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#291]
```
// TODO: we need to work out how to upload a tar file
```

https://github.com/filecoin-project/bacalhau/blob/fba8654baa6fbd9daa9b7df838c8adc138c06536/pkg/ipfs/http/httpclient.go#L199

**Comment by wdbaruni** [comment]
It seems we are not longer using ipfs http client, and this is no longer an issue. Closing
