### ISSUE TITLE
Support Nvidia GPUs in the docker driver

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#292]
## Assumptions

* NVidia only
* Docker run only
* Only support GPU requests of `1.0` - no support for fractional GPUs, multi-gpus, or any other configuration

## Plan

* [x] Spin up test GPU VM (T4 Tesla)
* [x] Hacky Install nvidia-docker2
* [x] VSCode SSH into VM and install bacalhau dev
* [x] Start devtest mode
* [x] Add GPU limits to `CapacityManagerConfig` - allow the node to specify the number of GPUs to use - only support single GPU, non-fractional for now, 1.0 only valid value
* [x] Add GPU limit options to serve command
* [x] Add a `--gpu` flag to the docker run command that works in exactly the same way as the [docker flag](https://docs.docker.com/config/containers/resource_constraints/#expose-gpus-for-use). For now, this will be a hard-coded string, if GPU mode is enabled. No configuration.
* [x] Test using simple nvidia-smi container
* [x] Docs to explain GPU requirements on a node
* [x] Docs to explain running GPU jobs for users

## Questions

* [x] No changes required for `JobSelectionPolicy`

## Future Concerns

* Do we want to offer users free use of a GPU node in a cluster?
* How do we support device selection?
* How do we account for multiple GPUs in use, when they are id'ed by "slot"
* How do we account for the executor CUDA version and container cudart version? (CUDA is not backwards compatible with cudart)
* Really hard to test GPU functionality, because the system-level stuff isn't injected. I.e. you need a GPU to return anything other than 0 for the various "does my system have a GPU" calls.

**Comment by wesfloyd** [comment]
Adding notes on use cases we can unlock via GPU support:
Algovera ML training
[Cell Modeling](https://github.com/cellmodeller/CellModeller/wiki)
[Neutrino Detection Simulation](https://github.com/DUNE/larnd-sim)
And potentially LabDAO partner integration

**Comment by aronchick** [comment]
Should we have a summary GPU issue? #293 too
