### ISSUE TITLE
production disk snapshots not being created

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#294]
There are no disk snapshots being created in the `bacalhau-production` project:

![image](https://user-images.githubusercontent.com/1676629/176164617-ff49e2f1-98ae-4842-967f-f9c0e582b597.png)

This is even though there is a snapshot schedule that shows the 3 disks being used:

![image](https://user-images.githubusercontent.com/1676629/176164792-8f7bca97-5051-41fd-8bb9-15cba507568b.png)

**Comment by enricorotundo** [comment]
```
You can only use guest-flush on disks attached to instances with supported operating systems.  
Make sure you have the latest image version and agent installed with required services (e.g. VSS for Windows).
```

Ref:
* internal: https://console.cloud.google.com/logs/query;query=%22disk%22%0AprotoPayload.methodName:%22ScheduledSnapshots%22;timeRange=2022-06-01T08:56:24.006Z%2F2022-08-17T09:56:24.006Z;cursorTimestamp=2022-08-15T23:37:51.138745Z?project=bacalhau-production
* external: https://serverfault.com/questions/1031951/google-cloud-compute-engine-persistent-disk-snapshot-schedule-not-working

**Comment by enricorotundo** [comment]
Ok. Snapshots were taken correctly.

<img width="1374" alt="Screenshot 2022-08-18 at 11 12 09" src="https://user-images.githubusercontent.com/4340327/185357862-29ed9126-735a-4c46-b1d8-34a0f7f32279.png">
