### ISSUE TITLE
Basic libp2p based system for communicating “I want to run a job”

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#3]
- [x] Client submits to network
- [x] ipfs job submit - where does it go?
- [x] I.e. mempool for jobs
- [x] Deliverable: There’s a binary you can invoke that listens and it can join a network of other servers on the network and a CLI that can trigger “I got a message” and everyone can get the message

**Comment by lukemarsden** [comment]
Demo! https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1642786497013000
