### ISSUE TITLE
github bot for performance deltas

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#311]
We care about performance now. So how are we going to avoid regressing it?

Find and reuse, or build a GitHub bot (or action) that posts performance results & deltas against latest main on PRs automatically. 

For the performance tests themselves, we can use the new scale testing framework at https://github.com/filecoin-project/bacalhau/tree/copy-before-sharing-pointer/benchmark_hack (or benchmark_hack folder on main once that branch is merged).

For quick tests we can use `make devstack-noop`, but it's worth having real container tests too (even if it's just `bacalhau docker run busybox /bin/true`).

Where to run them? What runs them? We should have a dedicated physical server for running benchmarks, and we could attach it as a github actions runner, with max concurrency = 1. Where to store the results of the runs? Maybe on GCS? And the GitHub bot runs in GHA and reads from GCS to get the files for main to make the comparison with the current branch under test. The files on GCS could be the raw json files that explode.sh writes and we could adapt `parse.py` to do the comparison.

**Comment by lukemarsden** [comment]
From @aronchick:

> perf tracking discussion - ok, looked at my old project and talked to some folks internally, i think the BEST solution we have (for now) is building a new workflow that runs the perf test and then writes the results to a repo (or the main repo).
> e.g. https://github.com/dapr/dapr/blob/master/.github/workflows/dapr-perf.yml


https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1656607499304239

**Comment by aronchick** [comment]
finished(-ish).
