### ISSUE TITLE
Install from HEAD when deploying to development cluster in CI

### ISSUE THREAD

**Issue by Bubblyworld** [filecoin-project/bacalhau#312]
Currently CI deploys to the bacalhau dev cluster whenever something is merged into `main`, but deploys the version of bacalhau in `development.tfvars`, which is fixed. We should be deploying from the repo HEAD instead (but only for the development cluster, of course).

**Comment by Bubblyworld** [comment]
![Uploading Screenshot 2022-06-30 at 13.52.07.png…]()

**Comment by Bubblyworld** [comment]
<img width="382" alt="Screenshot 2022-06-30 at 13 52 07" src="https://user-images.githubusercontent.com/6214591/176711212-3e07bb34-eb77-4f41-905c-02593e5f328b.png">

**Comment by simonwo** [comment]
Commentary: we're not doing automatic deployments to the dev cluster. It's up to whoever wants to use the dev cluster to update it to whatever version they want.
