### ISSUE TITLE
wait for job to finish and print output automatically

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#314]
we should totally give bacalhau run a --follow parameter to follow the logs / --wait to wait for the command to finish and then just print the result (or a -d for “run in the background”, like docker, and have the default be to show the results)

step 1:
- [x] wait for job to finish and then fetch results (--wait)

step 2:
- [ ] [implement log streaming (--follow, much bigger project)](https://github.com/filecoin-project/bacalhau/issues/448)

**Comment by lukemarsden** [comment]
Desired behavior:
```
bacalhau run ubuntu echo hello
hello
```

**Comment by lukemarsden** [comment]
Would be nice to make this work for `bacalhau run python` as well

**Comment by wdbaruni** [comment]
I am closing this issue since log streaming is a big project, and we have a dedicated issue for it
