### ISSUE TITLE
cancelBid

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#319]
am braindumping here whilst it's in my mind - am currently plugging in "resource limits" so a compute node will not run jobs as fast as it sees them

there will be a background control loop that will bid on jobs after a period of time that they were first seen by the compute node

so - after 5 mins, job X is bid on - the compute node will only bid on jobs that it has space to run - to avoid over promising and under delivering - but the requester node might take some time to accept the bid - in which time more jobs have arrived which we might want to bid on instead

equally - we might decide to over promise - and actually bid on more jobs than we have space for to try and get an accepted bid as quick as possible - and then all the bids are accepted and now we don't have enough space to run all the jobs we should be running

for both of these scenarios - we could do with a `CancelBid` function in the transport that enables a compute node to say "actually I am not going to run this job after all" - that leaves a requestor node open to accept the bid of another compute node

**Comment by Bubblyworld** [comment]
Might be relevant: https://github.com/filecoin-project/bacalhau/issues/320

**Comment by binocarlos** [comment]
closing in favour of #320
