### ISSUE TITLE
Formalise the JobState state machine.

### ISSUE THREAD

**Issue by Bubblyworld** [filecoin-project/bacalhau#320]
Something me and @lukemarsden were talking about at some point on [slack](https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1655805109145659): at the moment the transition logic for different `executor.JobState`s is implicit in `requester_node.go` and `compute_node.go`. This makes it hard to reason about, for instance when exactly should a node consider a job "ignorable" in the sense it should stop bidding/listening to events for it? When should compute nodes retry bids for a job that has been stale for a while?

I think it would help if we formalised the legal transitions and transition logic for JobStates in some kind of state machine. It would make answering these questions much easier, and paves the way to ensuring guarantees like eventual termination of jobs (at the moment I'm pretty sure they can hang in all sorts of weird ways, especially in edge-case scenarios like node crashes).

**Comment by aronchick** [comment]
State machine would also make reporting on status/watching/etc much easier for clients too

**Comment by aronchick** [comment]
Needed for this too #290

**Comment by aronchick** [comment]
Also needed here #285

**Comment by aronchick** [comment]
Also here? #143

**Comment by wdbaruni** [comment]
Also needed here #487

**Comment by wdbaruni** [comment]
Timeouts are introduced in https://github.com/filecoin-project/bacalhau/pull/1061. Retries require more significant changes that we an revisit in the future if there is a demand for it.
