### ISSUE TITLE
Interactive Bacalhau CLI

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#321]
For Discussion of the doc: [Bacalhau-Interactive-CLI](https://docs.google.com/document/d/1P187KqpVHAhkF4Asml_CKnswMnOY4I-Tl3s-nhFLU-A/edit )

cc @aronchick

**Comment by aronchick** [comment]
@lukemarsden do we want to link to Google docs? Or have all discussion in here?
