### ISSUE TITLE
Serving a website (of some kind) from Bacalhau?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#326]
Absolutely mad idea (even despite there not being networking) -
 
https://github.com/gocopper/copper?utm_source=tldrnewsletter

Go binary that includes an entire website. Could this be used for auto rendering pages? E.g. push your website to Bacalhau, and we'll render every page as a PDF and push it to IPFS? Or something similar?

Just thinking crazy.

**Comment by wesfloyd** [comment]
+1 If we can implement long running containers (such as for web serving), this would open a wide range of use cases (and users) for Bacalhau.
