### ISSUE TITLE
Remove t.Skip("TEMP_SKIP_FOR_NULL_POINTER_FAST_FAIL_TEST")

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#336]
If anyone knows how to fast fail the tests, or knows why this throws null pointer errors in CircleCI only, please pick this up. When done, search and remove this line from all tests.

t.Skip("TEMP_SKIP_FOR_NULL_POINTER_FAST_FAIL_TEST")

**Comment by aronchick** [comment]
⬆️ @Bubblyworld @binocarlos @lukemarsden

**Comment by aronchick** [comment]
REMINDER, this works fine locally, but breaks in CircleCI. I don't know why.

**Comment by Bubblyworld** [comment]
I _think_ this is okay - I've run the tests a bunch locally after removing the `Skip(...)`s, and it runs on CI fine too.
