### ISSUE TITLE
api versioning

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#343]
We are already hurting a bit because of a lack of api versioning: https://github.com/filecoin-project/bacalhau/issues/340

We really need a solution for older CLI binaries out in the wild that will submit requests in an older data structure than the server understands (otherwise known as api versioning)

**Comment by lukemarsden** [comment]
once we cut a 1.x release we can start ensuring backward compatibility with older clients, doing that prematurely will just slow us down

**Comment by aronchick** [comment]
i'm all for skipping that, but we should at least check during communication because there are many errors that seem inscrutable at first, that could be just version mismatch. Just reporting the fact that two binaries aren't on the same version is probably plenty.
