### ISSUE TITLE
should system.ListenAndServeMetrix take ctx?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#352]
```
		// TODO: should system.ListenAndServeMetrix take ctx?
```

https://github.com/filecoin-project/bacalhau/blob/117a53f7eac3b9650d5264adb8dc5f1958f6f32b/cmd/bacalhau/serve.go#L201

**Comment by Bubblyworld** [comment]
Probably a no, given that it uses a `CleanupManager` for lifecycle management 👀

**Comment by aronchick** [comment]
SG, feel free to remove the TODO and close this if you're sure :)

**Comment by wdbaruni** [comment]
Currently `system.ListenAndServeMetrics` takes a ctx. Closing the issue
https://github.com/filecoin-project/bacalhau/blob/main/pkg/system/metrics.go#L16
