### ISSUE TITLE
publicapi: 400 body returned from API server: client's signature is invalid

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#358]
building from source
<img width="960" alt="image" src="https://user-images.githubusercontent.com/79689323/177791982-ebb0b366-88c5-4792-ab18-34bae0eb69ee.png">

using the binary
<img width="948" alt="image" src="https://user-images.githubusercontent.com/79689323/177792137-089eedfc-3f9b-49ab-b326-77ef5f0bb8c7.png">

**Comment by aronchick** [comment]
if you’re building from source, you also need to be communicating to a local devstack server - otherwise you’ll be out of so in a new shell do, `./bacalhau devstack` .and in the first shell, paste in the shell variables
