### ISSUE TITLE
Support for interactive mode in the docker backend

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#376]
Users should be able to this
![image](https://user-images.githubusercontent.com/79689323/178666933-e5f094d8-b081-4e28-9b9d-50e1e1652d7e.png)
`bacalhau docker run -it python /bin/bash`

After Apply this the UX will improve 10x

**Comment by aronchick** [comment]
Not possible, no networking.

**Comment by aronchick** [comment]
Does the container run locally? Why does running this on bacalhau change debugging?
