### ISSUE TITLE
Proposed UX change

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#384]
Today, we have the following profile for a job:

```
bacalhau docker run \
  -v QmeZRGhe4PmjctYVSVHuEiA9oSXnqmYa4kQubSHgWbjv72:/input_images \
  -o results:/output_images \
  dpokidov/imagemagick \
  -- magick mogrify -resize 100x100 -quality 100 -path /output_images /input_images/*.jpg
```

I propose the following is a better experience

```
bacalhau docker run \
  -i QmeZRGhe4PmjctYVSVHuEiA9oSXnqmYa4kQubSHgWbjv72
  dpokidov/imagemagick \
  -- magick mogrify -resize 100x100 -quality 100 -path /output /input/*.jpg
```

This means:
* Change `-v` (for input) to `-i` (for CID) (still optional, you could, theoretically run a job with no CID)
* Change the default `-o` to be default `output:/output`

Thoughts?

**Comment by lukemarsden** [comment]
what if you want to mount multiple CIDs to the same job?

**Comment by lukemarsden** [comment]
why don't we keep `-v` but also add `-i` as an alias and allow not specifying `:` for single inputs
we can also add a default `/output` output but still allow people to specify `-o` if they want to mount it somewhere else

**Comment by lukemarsden** [comment]
i.e. let's make backward compatible changes which support your goal of a simpler UI

**Comment by aronchick** [comment]
Right - it's pretty easy to bake in default if nothing is listed after the :

My thought is we're not seeing almost any reason to list an output, and inputs are cids only (and, for now, just one cid).

Should be easy to achieve what you describe though

**Comment by aronchick** [comment]
Also, what about if we make `image` optional as well? e.g. would could just run everything on ubuntu unless you specify
