### ISSUE TITLE
Why is ctx unused if it's passed in? Shouldn't cm do something with it?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#393]
```
		// TODO: Why is ctx unused if it's passed in? Shouldn't cm do something with it?
```

https://github.com/filecoin-project/bacalhau/blob/fb9449fff272e68a69cd13fb0b650e3edb2da6c1/pkg/devstack/devstack.go#L173

**Comment by lukemarsden** [comment]
@enricorotundo  can you check this? let's just make sure we're not leaking anything. don't spend more than 30 minutes on it

**Comment by lukemarsden** [comment]
not a problem if the resource is only in-process
