### ISSUE TITLE
Writting Examples for commands inside the CLI

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#395]
Similar to examples in kubectl [command] --help
https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/apply/apply.go#L192
<img width="660" alt="image" src="https://user-images.githubusercontent.com/79689323/179820427-6bd617ff-cf62-44d9-8c35-eb4ee831b148.png">

**Comment by lukemarsden** [comment]
we have fields for this now, please check if they're all filled in :)
