### ISSUE TITLE
Labels should be useful in Lists

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#402]
ETA: 2023Q1

Hijacking issue

- [ ] Improve docs around labels
- [ ] Make them useful in lists

-l, --labels strings           List of labels for the job. Enter multiple in the format '-l a -l 2'. All characters not matching /a-zA-Z0-9_:|-/ and all emojis will be stripped.

you can add labels in bacalhau docker run but what to do with them later ?
 @aronchick  can you please can you provide details of how to use it after you apply labels to your job ?

**Comment by aronchick** [comment]
Can you respond with what's confusing?

**Comment by js-ts** [comment]
can explain more what happens to the labels after you've run a job

how they can be used  in some other way than  bacalhau docker run
<img width="584" alt="image" src="https://user-images.githubusercontent.com/79689323/180464167-9e57c0cc-0929-48e0-84cd-29084315b9c5.png">

for example to rerun a job
<img width="433" alt="image" src="https://user-images.githubusercontent.com/79689323/180460781-24d1d25f-3715-4626-8cea-8ee01636678b.png">

or to get a jobs results

`bacalhau get -l hello`

**Comment by aronchick** [comment]
@aronchick add it to list

**Comment by simonwo** [comment]
Done in #1475.
