### ISSUE TITLE
Accepted job missing from "bacalhau list" results

### ISSUE THREAD

**Issue by wesfloyd** [filecoin-project/bacalhau#407]
Steps to reproduce:
- Submit job to bacalhau cluster, e.g. "bacalhau docker run ..." (image attached)
<img width="1352" alt="image (1)" src="https://user-images.githubusercontent.com/260568/180646328-b608c66e-5c0d-498b-b980-69876a25b545.png">
- Observe the job is accepted and assigned an ID
- Execute command "bacalhau list" 

Expected behavior:
- Submitted job should appear in the resulting list

Observed behavior:
- Submitted job does Not appear in the resulting list
- (May be related to internode communication on job state?)

*Note: this behavior occurs **intermittently**. Raising this issue to track the behavior. Slack [discussion reference here](https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1658177018527379).

**Comment by lukemarsden** [comment]
is this still happening?

**Comment by wesfloyd** [comment]
@lukemarsden no, I have not seen this issue occur recently
