### ISSUE TITLE
refactor test tooling

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#410]
ETA: 2022Q4

We currently have test tools scattered in various places in the codebase - the tests in `pkg/test/devstack` will start a full stack with ipfs and docker whereas other tests (e.g. `pkg/publicapi`) will start a noop stack.  Also - when testing CLI commands - we are polluting the global variables initialised by cobra which then affects the next test that is run.

What we need is a single package with a good name (e.g. `testtooling`) that offers an easy way to spin up and cleanly shutdown:

 * a full devstack with docker executor and ipfs storage
 * a noop stack
 * a CLI command

There are various places in the code that currently spin up a full docker & ipfs devstack when they don't actually need to do that - for example tests that check the scheduler is working well don't need to run a docker container.

The `noop` executor offers hooks into all of it's actions and this should be enough to use to tests like these - so as part of refactoring the test tooling - let's also take the chance to make sure each test is using the absolute minimum stack that it actually requires.

**Comment by aronchick** [comment]
I'm happy to take on this grunt work of swapping everything out and getting things to pass. But can you specify the design you're thinking? 100% test tooling for tests?

I do like going through the CLI to test things though - it forces avoiding any hidden states that may carry over from the test to the implementation (though, as you point out, it risks .

**Comment by aronchick** [comment]
This is pretty interesting - did a bunch of looking at kubectl, and the only way they do it is to create a cmd factory, and allow for dependency injection at the point of tool execution (https://github.com/kubernetes/kubectl/blob/f89fc21e9c51d313e923eb93d1ae83754be62019/pkg/cmd/apply/apply_test.go#L89)

It's good, but it's a lot of abstractions.

**Comment by simonwo** [comment]
I'm closing this because I think we've addressed much of the feedback:

> What we need is a single package with a good name (e.g. testtooling) that offers an easy way to spin up and cleanly shutdown:
>
>    * a full devstack with docker executor and ipfs storage
>    * a noop stack
>    * a CLI command

That is offered by the `test/suite` and `test/devstack` packages now.

> There are various places in the code that currently spin up a full docker & ipfs devstack when they don't actually need to do that - for example tests that check the scheduler is working well don't need to run a docker container.
>
> The noop executor offers hooks into all of it's actions and this should be enough to use to tests like these - so as part of refactoring the test tooling - let's also take the chance to make sure each test is using the absolute minimum stack that it actually requires.

This was done in #1036, and there is now [more documentation of how to use the Noop Executor for testing](https://pkg.go.dev/github.com/filecoin-project/bacalhau@v0.3.16/pkg/test/scenario#example-package-Noop).
