### ISSUE TITLE
Input CID shall not contain subpath

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#416]
`docker run -v QmToHuqbiBvvL2LPHxdNXKQKvKicTRvB3hh2YdVBUk7rkw/input:/project/input [...]` creates a (evenutally failing) job even though `QmToHuqbiBvvL2LPHxdNXKQKvKicTRvB3hh2YdVBUk7rkw/input` ~is not a valid CID part because it shall not contain any `/`.~ (issue originally raised by @wesfloyd)

Should validate all user inputs instead.

**Comment by enricorotundo** [comment]
Duplicate of https://github.com/filecoin-project/bacalhau/issues/342

**Comment by enricorotundo** [comment]
Reopening this. Just realized this is not really a duplicated issue because this one pertains to the case of having a subpath appended to a CID e.g. `QmToHuqbiBvvL2LPHxdNXKQKvKicTRvB3hh2YdVBUk7rkw/input`

@binocarlos had the idea of taking `-v <cid>/hello:/hello` and resolving `<cid>/hello` into the corresponding CID by using https://github.com/ipfs/go-cid/blob/master/cid.go#L166

**Comment by lukemarsden** [comment]
Yeah, I vote we don't support this more complex syntax right now. Just failing, with a more informative user error, so the user knows how to update their job, is perfectly fine at this stage.

**Comment by lukemarsden** [comment]
btw you might be able to simply validate that the CID is a certain length to begin with, and fail for any non-standard string lengths?

**Comment by enricorotundo** [comment]
Unluckly can't use just string length because in CID v0 fixed, in v1 depends on the multibase/codec. https://docs.ipfs.tech/concepts/content-addressing/#identifier-formats
