### ISSUE TITLE
Should we refactor all this waiting out? I worry about putting this all here - feels like we're overloading the surface of the CLI command a lot.

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#424]
```
		// TODO: Should we refactor all this waiting out? I worry about putting this all here - feels like we're overloading the surface of the CLI command a lot.
```

https://github.com/filecoin-project/bacalhau/blob/03ce4984cb259e21d2ff76f9f1d46a575f495ecf/cmd/bacalhau/docker_run.go#L467

**Comment by binocarlos** [comment]
@aronchick I'm currently in the process of refactoring this out because I'm adding sharding and that involves changing the nature of what it means to "wait for the state of a job to reach X"

**Comment by binocarlos** [comment]
You can see how this function looks in the refactored branch here: https://github.com/filecoin-project/bacalhau/blob/127-sharding/cmd/bacalhau/docker_run.go#L209
