### ISSUE TITLE
Can you explain what the below is doing? Please comment.

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#425]
```
			// TODO: Can you explain what the below is doing? Please comment.
```

https://github.com/filecoin-project/bacalhau/blob/03ce4984cb259e21d2ff76f9f1d46a575f495ecf/cmd/bacalhau/docker_run.go#L487

**Comment by aronchick** [comment]
This entire block seems weird - why do you loop on cidl but then only take one?

**Comment by js-ts** [comment]
https://github.com/filecoin-project/bacalhau/issues/314
so this block waits for a job to finish and prints the stdout to the console

**Comment by js-ts** [comment]
thats the initial implementation of it, so just print one CID
I think it shoould be used for single node job for now

**Comment by aronchick** [comment]
please don't use fmt.Println(), please use cmd.Println()

**Comment by js-ts** [comment]
updated
