### ISSUE TITLE
deploying to dev terraform cluster should not happen from non-main branch builds in CI

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#434]
what it says ^

**Comment by enricorotundo** [comment]
## Problem

There're a number of CircleCI workflows (`dev_branches`) that run whenever anything happens to a branch != main.
 
<img width="1430" alt="Screenshot 2022-08-08 at 16 46 56" src="https://user-images.githubusercontent.com/4340327/183445847-084936dd-d041-400d-88d9-38b893247f5b.png">

The tf state file for `development` cluster on gcp bucket confirms there's has been a deployment to dev-cluster:

<img width="1680" alt="Screenshot 2022-08-08 at 16 51 55" src="https://user-images.githubusercontent.com/4340327/183447393-c9e28d5c-f83d-4b5f-b33d-e9bab1715ba8.png">

**Comment by aronchick** [comment]
but isn't the idea here that we have a dev cluster which is up to date SORT OF? E.g. if you're on a branch and want to see if your stuff will run properly when not on devstack. Having EVERY branch do this probably is too much.

maybe we need a command to bounce the dev cluster (for testing). Or is this all too crazy/unnecessary?

**Comment by enricorotundo** [comment]
TBH I've never used dev-cluster so far. May be just me but I prefer [to spin up a short-lived cluster](https://github.com/filecoin-project/bacalhau/tree/main/ops#stand-up-a-new-short-lived-cluster) and clean it up as soon as I'm done.
