### ISSUE TITLE
short and long ids

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#435]
currently it's not possible to investigate a job you can see in `bacalhau list --wide` because it doesn't give you the full id that you need to use with `describe` or `get` (to download the results)
* make `bacalhau describe` accept a shortened job id
* make `bacalhau get` accept a shortened job id
* make `bacalhau list --wide` show the long job id

**Comment by aronchick** [comment]
fixed with this https://github.com/filecoin-project/bacalhau/commit/eabf1b45bd4e74b8679b8b16528120594e7e11b4
