### ISSUE TITLE
Output volumes called "outputs" are colliding

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#440]
We automatically [add an output volume](https://github.com/filecoin-project/bacalhau/blob/f2aa15c985115669797fc3939b213faaeab7a43a/cmd/bacalhau/docker_run.go#L424) to each job - which is nice because it means the user has to type less if they know it's there

However - if someone (like me) doesn't realise that happens and then thinks:

> I will add an output volume called "outputs"

Then it collides and the system errors with a message about overlapping docker mounts

We should check if the user has not already given us an output volume before automatically adding one

**Comment by aronchick** [comment]
can you repro? i think this is fixed
