### ISSUE TITLE
bacalhau get is hanging

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#441]
After processing some videos - I have about 30Mb of results from my job...

I was running the job with `--wait` which will try to use the `download` codepath so it can print stdout when finihsed

The problem is the `bacalhau get` code is hanging trying to download the CID - even after adding `--timeout-secs 100000`.  Using the ipfs cli however downloads it right away:

```
kai@xwing:~/projects/protocol-labs/example-files$ ipfs --api /ip4/127.0.0.1/tcp/34079 get /ipfs/QmS2r4MNtbE1dFERwEiMnhFY9dpzFQM8WjHQgDTu92LvDw/outputs                                                                                                                                             
Saving file(s) to outputs
 28.13 MiB / 28.13 MiB [==============================================================================================================] 100.00% 0s
 ```

**Comment by lukemarsden** [comment]
is this with devstack? does the local ipfs client need to be educated about devstackiness?

**Comment by binocarlos** [comment]
> is this with devstack? does the local ipfs client need to be educated about devstackiness?

this is an excellent point thank you!

**Comment by wdbaruni** [comment]
@binocarlos is this still an issue?
