### ISSUE TITLE
Add release instructions

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#457]
* [ ] Binary release documentation
* [ ] Public test cluster release instructions

**Comment by enricorotundo** [comment]
[#438](https://github.com/filecoin-project/bacalhau/pull/438) involves Terraform init scripts and some new env vars. How to deploy without necessarily cutting a new release?

**Comment by lukemarsden** [comment]
You can deploy new terraform without having to bump the release version
