### ISSUE TITLE
remove import cycle errors

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#463]
The `executor` package has become the defacto home for core job spec types...

It also references:

```
import (
	"context"
	"time"

	"github.com/filecoin-project/bacalhau/pkg/capacitymanager"
	"github.com/filecoin-project/bacalhau/pkg/storage"
	"github.com/filecoin-project/bacalhau/pkg/verifier"
)
```

The problem is to reference core system types like `JobState` - we have to say `executor.JobState` - which, if used from any of:

 * capacitymanager
 * storage
 * verifier
 
Causes an import cycle error.

This cropped up when I wanted part of the verifier interface to accept a `executor.JobState` argument - boom can't do it

We could move core types to a `types` package that does not reference any other bacalhau packages.  The problem with that is the `JobSpec` mentions `Engine` - which points at the executor enumeration of engine types - which by default should live in the executor package.

We could move enumerations of different engine types (such as in executor, storage, verifier and publisher) - also to the types package.  Or we could solve it another way - either way we should be able to mention core data types from any package without import cycle loops.

**Comment by aronchick** [comment]
i was just thinking this as well. 

qq - i think we should have a "cli parameters" job type, btw. That would make reseting after tests much more sane, and feels a lot more elegant than a million private variables at the top of each command. Thoughts?
