### ISSUE TITLE
call executor IsInstalled and rename

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#464]
ETA: 2023Q1

Currently - the compute node is bidding on jobs without calling the `IsInstalled` method of the executor - this is meaning jobs are being bid on even when Docker is not running

As well as call this method (as part of the compute node job selection) - we should rename it to `IsReady` - because there is ambiguity between being installed and running.  The docker executor `IsReady` method would check both:

 * that docker is installed on the system
 * that it's up and running and ready to start containers
 
both as part of the `IsReady` method of the executor interface

**Comment by wdbaruni** [comment]
It seems that now we are checking if the executor is installed before bidding on the job:

Compute node calls `GetExecutor` during `SelectJob`:
https://github.com/filecoin-project/bacalhau/blob/main/pkg/computenode/computenode.go#L464

`GetExecutor` implementation:
https://github.com/filecoin-project/bacalhau/blob/main/pkg/executor/executor_provider.go#L41

Also `IsInstalled` will return true not only if docker is installed in the machine, but also when it is running and ready:
https://github.com/filecoin-project/bacalhau/blob/219a5339fdce082336bf6a37c096e157ca824226/pkg/docker/utils.go#L32

Should we close this issue? cc: @binocarlos

**Comment by wdbaruni** [comment]
hmm .. it seems we have a bug in our bidding logic where nodes do bid on jobs even when docker wasn't installed https://github.com/filecoin-project/bacalhau/issues/691

**Comment by wdbaruni** [comment]
We have logic that calls docker executor to estimate the job disk requirements before checking with the bidding strategies, which throws an error instead of just deciding not to bid. Will fix that

**Comment by wdbaruni** [comment]
Fixed by #1401. Asking the bid strategy is now broken into two phases: `ShouldBid` is called before calculating the job resources which will reject jobs early if an engine is not supported, and `ShouldBidBasedOnUsage` after the resource usage is calculated
