### ISSUE TITLE
Remove "waitAndPrintOutput"

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#466]
https://github.com/filecoin-project/bacalhau/blob/dd2e3f5d2971cf55f226524903578ced7281aeb1/cmd/bacalhau/docker_run.go#L38

I'm not sure this makes sense. Should we really have this as an entire flag in our system? If people really want this, shouldn't we just do suggest it via piped shell commands?

cc @lukemarsden

**Comment by js-ts** [comment]
I recommend not removing it (for now) and why remove it if it works ?

the sharding demo video uses it
https://www.youtube.com/watch?v=sIeBtWJS50A
if we remove this will make commands in the video not work
https://github.com/filecoin-project/bacalhau/tree/main/examples/video-filter-sharding

**Comment by lukemarsden** [comment]
The goal of this flag was to reproduce the simplicity of 
```
docker run ubuntu echo hello
hello
```

You get to see your output/errors straight away, without messing around with `bacalhau get` and copying ad pasting IDs around in the terminal. So, unless I'm misunderstanding you, I suggest we don't remove this flag.
