### ISSUE TITLE
consider libp2p topology and protocols

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#488]
ETA: 2023Q1

We are currently operating on a "broadcast everything to everyone" mode over gossipsub - this has the following limitations:

 * it will not scale
 * there is no way of targeting a single node
 * we cannot send large amounts of data
 
Some things like "Job Created" are suited to broadcast mode - because everyone will want to hear about the new job.

Other things like the bidding process and results submission could be handled using a direct requester node <-> compute node connection - much like ipfs uses [bitswap](https://github.com/ipfs/go-bitswap) to send file data to other nodes - we could use our own libp2p protocol to negotiate things like bid acceptance/rejection, verification & results submission and results acceptance/rejection.

The first pass at implementing a libp2p protocol for bacalhau should consider these issues:

 * ensuring that events are recieved by the nodes that care about those events e.g. what if a "complete" event is dropped and the requester thinks the job has got stuck but all that happened was the complete message was lost
   * what happens when we replace gossipsub with a smart contract that emits events?
 * allowing for the private transfer of possibly large verification artifacts between compute & requester nodes - do we just use bitswap for this?
 * if we do just use bitswap then now we need a DHT of the multiaddresses for each node like ipfs uses

**Comment by wdbaruni** [comment]
Will be resolved by https://github.com/filecoin-project/bacalhau/issues/1092
