### ISSUE TITLE
Mocking docker/libp2p/ipfs for non-critical situations

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#493]
https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1660581928607759

Kai:

* sometimes we want to test features that are not deployed in production or staging (e.g. on a feature branch)
  * so for this we only want those tests to target an in process stack that has said feature
* a LOT of our tests could be using mocks for Docker, IPFS and libp2p because they are testing logical flow and don't really care if it's real docker / IPFS
  * I think we should do this as much as possible to remove test flakes
  * All tests that fall into "could use mocks" territory don't really care where they are run (and should never flake and be 100% deterministic)
* any tests that actually DO need to test the full, authentic Docker, IPFS & libp2p stack could now be targeting production and or staging
  * I view these tests as the MOST valuable - i.e. if I ran a job for real would it actually work kind of tests

**Comment by binocarlos** [comment]
there is a template for doing this that lives in the [compute node tests](https://github.com/filecoin-project/bacalhau/blob/741062b38d6b278e2b843bb7a441f1ccbbc75b3c/pkg/test/computenode/utils.go#L79)
