### ISSUE TITLE
6. Distributed data based job selection (orchestration)

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#5]
- [x] Job selection for a miner and execution, I’ve got a chunk of data so i’m eligible to consider this job
- [x] Do I have this data?
- [x] Do I want to execute it?
- [x] Deliverable: A compute node knows what CIDs it has and therefore can pick work from the mempool

**Comment by lukemarsden** [comment]
We'll do this for IPFS initially.

**Comment by lukemarsden** [comment]
Done for IPFS
