### ISSUE TITLE
support for other container registries

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#501]
like https://catalog.ngc.nvidia.com/
and more...

**Comment by lukemarsden** [comment]
We already do, just name the image like quay.io/foo/bar:tag

**Comment by js-ts** [comment]
@lukemarsden sorry didn't post the screenshot
Its not working
<img width="630" alt="image" src="https://user-images.githubusercontent.com/79689323/185115595-3e8ba5e0-9867-48ec-95c3-3770668a4b31.png">

If i'm making any mistakes in the command can you try it yourself
with your own image https://catalog.ngc.nvidia.com/orgs/partners/containers/dotscience-runner

**Comment by aronchick** [comment]
@js-ts please post the text along with the screenshot
