### ISSUE TITLE
need opentelemetry spans in every function

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#509]
every function, especially those in computenode requesternode controller ipfs storage and verifier, need opentelemetry spans, many are missing. this makes the spans we see much less useful than they could be. add spans to all the code that gets touched in a typical execution

**Comment by aronchick** [comment]
@enricorotundo are you working on this? i'm happy to pick it up if not.

**Comment by enricorotundo** [comment]
go ahead  👍
