### ISSUE TITLE
calculate network size dynamically

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#512]
ETA: 2023Q1

new performance improvements require nodes to know a lower bound on the size of the network, currently we hard-code this in https://github.com/filecoin-project/bacalhau/pull/511 but we need to calculate this dynamically. Until we fix this, big networks won't be fast again (since I just changed that number from a hard-coded 250 to a hard-coded 3)

**Comment by lukemarsden** [comment]
https://github.com/filecoin-project/bacalhau/pull/511/commits/262477d99d1095e87f3c904bfd5b1f7e776ab9bb

**Comment by lukemarsden** [comment]
we can probably start by just keeping track of how many distinct node ids we've heard from in the last... say, 10 minutes? and use that in our calculation

**Comment by lukemarsden** [comment]
ah but then we should probably also make nodes heartbeat on the network every minute or so so that quiet nodes don't disappear from the calculation

**Comment by binocarlos** [comment]
the heartbeat could contain info about "here is the capacity that I offer the network" - then we can:

 * know how many nodes there are
 * know how many resources there are across the whole network
 * know how many resources a single node offers
   * this will help requester nodes to accept certain bids based on each nodes reported capacity

**Comment by aronchick** [comment]
fascinating problem - how does K8s do this? Do kubelets heartbeat back to apiserver?

**Comment by lukemarsden** [comment]
Via etcd I believe yes

**Comment by wdbaruni** [comment]
This should not be a problem once we switch from GossipSub to direct calls for job negotiation

**Comment by wdbaruni** [comment]
I am closing this task as we shouldn't solve it since we will drop adding artificial latencies before bidding on jobs
