### ISSUE TITLE
Library change that caused a 3x slowdown in tests

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#517]
Is this a concern?

https://github.com/filecoin-project/bacalhau/compare/3ee32aa..61f26be

This change caused tests to go from ~90s to complete to ~300s to complete. (this is on-going)

![CleanShot 2022-08-22 at 16 13 00@2x](https://user-images.githubusercontent.com/51317/186035001-5a5c3462-d158-4496-9497-b42a04a97b6e.png)

**Comment by lukemarsden** [comment]
i think the tests went from failing straight away to passing after running for a few minutes
