### ISSUE TITLE
Clean up image example

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#530]
It's out of date - https://docs.bacalhau.org/demos/image-processing

Too many flags currently there - e..g -v, -i, and -o are no longer necessary.

**Comment by enricorotundo** [comment]
I've updated the example snippet at https://docs.bacalhau.org/demos/image-processing. Indeed, `-o` is no longer needed. @aronchick what about the `-v` flag? Unless I'm missing something I don't think we can do without 🤔

**Comment by enricorotundo** [comment]
Let me know if I can close this one

**Comment by philwinder** [comment]
Example captured in https://docs.google.com/spreadsheets/d/1QwOAYlFOpoJbWAGs5W1KdctDUouKOwLzxgTyAhyHD6Q/edit?pli=1#gid=0
