### ISSUE TITLE
-v and -u flags don't work together

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#533]
When you try to use -v and -u flags together, 
because you wanted to mount from a CID as well as URL
only one of them mounts
```
bacalhau docker run \
--wait \
--download  \
-v QmZULkCELmmk5XNfCgTnCyFgAVxBRBXyDHGGMVoLFLiXEN:/hello-cid.txt \
-u https://gist.githubusercontent.com/js-ts/770930a9b98ce69d1a5116f693f027bf/raw/d4f7ba6fd788d99fb9dacb02fdf1fb2e7622f4e2:/hello-url.txt \
ubuntu ls
```
Results
```
bin
boot
dev
etc
hello-url.txt
home
lib
lib32
lib64
libx32
media
mnt
opt
outputs
proc
root
run
sbin
srv
sys
tmp
usr
var
```
Here we are trying to mount -v QmQtZKRPXehLU5JroBbzBCVdhNkgZT7m4MiSD7sUVxE3LD:/hello-cid.txt 
and -u https://gist.githubusercontent.com/js-ts/770930a9b98ce69d1a5116f693f027bf/raw/d4f7ba6fd788d99fb9dacb02fdf1fb2e7622f4e2/hello.txt:/hello-url.txt 

but as you can see in the results on the hello-url.txt got mounted and not the hello-cid.txt file

screen shot highlighting the hello-url.txt,  hello-cid.txt isn't there
<img width="959" alt="image" src="https://user-images.githubusercontent.com/79689323/187016100-8a3ea36c-c7b3-4620-b46e-7404bd96a4f9.png">

**Comment by aronchick** [comment]
If you execute the same commands without the -v, what is the output?
