### ISSUE TITLE
Plan content and examples

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#550]
See this thread for context: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1661961133663469

With the ultimate aim of increasing the number of users, we need to make some noise. First we need to create (approx) 5 examples/content that should take no more than 1 day per example.

There is some overlap with this issue: https://github.com/filecoin-project/bacalhau/issues/538

- [ ] Investigate current onboarding list and categorize by industry, use case, data type, or whatever.
- [ ] Develop several ideas for simplified examples that target personas in these catagories
- [ ] Get ideas from Wes and David and others based upon current work, e.g. caltech benchmarking
- [ ] Get agreement on priorities and shortlist
- [ ] Create a rough content calendar (i.e. just plan to make sure that it is feasible) and GH issues for each example

Notes:
Personas are scientific/researchers. Typically heavy in data, like seismic, life sciences. Content should be thought provoking. May also consider expanding to web3 folks. Content may be blogs, examples, videos, new content, status updates, results, etc.

**Comment by enricorotundo** [comment]
[David proposed to move ALL the examples to a dedicated repo (with tests)](https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1662140153234319?thread_ts=1662119932.257749&cid=C02RLM3JHUY). Currently examples are scattered all over the place, untested and sometimes outdated. 
I see tons of value in doing that.

**Comment by philwinder** [comment]
Closing this issue as we've switched priorities to work mostly on examples for now. We've captured them in a spreadsheet and will be working on them one at a time, with an issue for each one.

https://docs.google.com/spreadsheets/d/1QwOAYlFOpoJbWAGs5W1KdctDUouKOwLzxgTyAhyHD6Q/edit?pli=1#gid=0
