### ISSUE TITLE
Documentation facelift (docs.bacalhau.org & more...)

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#554]
### README

- highlight “What is Bacalhau”
- highlight Getting Started
- add references to the community on Slack
- more..

## Docs repo

- https://github.com/bacalhau-project/docs.bacalhau.org/issues/26
- https://github.com/bacalhau-project/docs.bacalhau.org/issues/24
- ... more generally all issues at 👇 
- https://github.com/bacalhau-project/docs.bacalhau.org/issues

**Comment by enricorotundo** [comment]
First round of facelifting completed ✅ 

1. new core repo README https://github.com/filecoin-project/bacalhau#readme
2. revised docs https://docs.bacalhau.org/ 
    * new getting started
    * updated image processing example
    * new structure  
    * new examples...
