### ISSUE TITLE
Node has no field or method IpfsNode

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#564]
Not sure how but CI checks for https://github.com/filecoin-project/bacalhau/pull/560 are ✅ , while [checks for main are ❌ ](https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/981/workflows/78dc1f00-a771-4a72-a810-50fbd1930dad/jobs/4762/parallel-runs/0/steps/0-104).

The problem(s) seem to be related to `Node` becoming `IpfsNode`:

```
make lint


pkg/devstack/devstack.go:286:33: node.IpfsNode undefined (type *"github.com/filecoin-project/bacalhau/pkg/node".Node has no field or method IpfsNode) (typecheck)
		swarmAddressesList, _ := node.IpfsNode.SwarmAddresses()
```

This was likely introduced in `7c08c62bab2077dd0726294be70b01224e85228d` because the previous commit `1afad5ef93564150d631e0eebc60f24612f64b74` works fine.

**Comment by lukemarsden** [comment]
<img width="898" alt="image" src="https://user-images.githubusercontent.com/264658/188468702-c4345f8a-8e3a-40b4-8611-d498380441f3.png">
