### ISSUE TITLE
Should this be cmd.Context()?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#580]
```
	// TODO: Should this be cmd.Context()?
```

https://github.com/filecoin-project/bacalhau/blob/7387c90b1b0098222f4c2ca1260a5dbf145956eb/pkg/system/tracer.go#L214

**Comment by wjam** [comment]
This probably should be as the context is used to shutdown the gRPC connection? Using the right context would mean having to rewrite the API in `pkg/system/tracer.go` so that the tracer is created during `PersistentPreRunE` on the command rather than on `init`.
