### ISSUE TITLE
The below is wrong - we need to shut down the trace provider and take the context from the caller.

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#581]
```
	// TODO: The below is wrong - we need to shut down the trace provider and take the context from the caller.
```

https://github.com/filecoin-project/bacalhau/blob/7387c90b1b0098222f4c2ca1260a5dbf145956eb/pkg/system/tracer.go#L254

**Comment by wjam** [comment]
Fixed in #1076. While handling of tracing may need to change due to #1029, the context can't be one from the client as this would have been cancelled as the process is being shutdown (as was the same with #594)
