### ISSUE TITLE
Rather than writing outputs to `shards`, write outputs to a specific folder named by the job and subdirs indexed by shard

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#585]
Currently, `bacalhau get` creates a `shards` directory and places jobs inside there. This is confusing because this implies that multiple jobs are all part of the same shard.

Instead, it should write files in the following format:
```
> tree .
- job-071c7cb6-100a-47d6-8ef9-c121a53487d8
| - shard-0-host-QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
|  | - stdout
|  | - stderr
|  | - exitCode
| - shard-1-host-fdsafdsafdsa
...
- job-789gfd
...
```

I.e. `./$JOB_ID/$SHARD_ID`

Tasks:

* [x] Reformat  the output directory structure to match the above
* [x] Alter the log message to tell the user where files have been written (logs should be on stderr)
* [x] Write the path to the directory where files have been written to stdout, to enable scripting. E.g. stdout would look like `./job-432hjk2...`

Context:

See: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1662633559568899

**Comment by philwinder** [comment]
Hang on, I think it already does that:

```bash
cid=$(bacalhau docker run ubuntu echo hello)
sleep 5
bacalhau get $cid
cid=$(bacalhau docker run ubuntu echo hello)
sleep 5
bacalhau get $cid
```

Results in:
```
❯ tree -L 1 shards
shards
├── job-071c7cb6-100a-47d6-8ef9-c121a53487d8-shard-0-host-QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
└── job-797c3b86-3ef6-44ac-a5f9-51c3319634bb-shard-0-host-QmdZQ7ZbhnvWY1J12XYKGHApJ6aufKyLNSvf8jZBrBaAVL
```

I.e. the job ID is already included in the directory name.

Also the log messages say:

```
11:52:12.752 | INF ipfs/downloader.go:195 > Combining shard from output volume 'outputs' to final location: '/Users/phil/source/filecoin-project/docs.bacalhau.org'
```

So the second request to adding the output to the CLI is valid, if that's what you want.

**Comment by lukemarsden** [comment]
It shouldn't write `shards, stderr, stdout, volumes` to the current working directory though. It should put all of the things inside a uniquely named directory. Otherwise if you run it twice you end up with (incorrectly) multiple shards inside the shards directory, but they're not actually shards of the same job, which is confusing

**Comment by philwinder** [comment]
Oh ok, that makes sense. It's the shards dir that's the issue then.

Can you suggest a preferred format then? Something like:

```bash
> tree .
- outputs
| - job-071c7cb6-100a-47d6-8ef9-c121a53487d8
|  | - shard-0-host-QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
|  |  | - stdout
job-071c7cb6-100a-47d6-8ef9-c121a53487d8
├── shard-0-host-QmYgxZiySj3MRkwLSL4X2MF5F9f2PMhAE3LV49XkfNL1o3
│   ├── exitCode
│   ├── stderr
│   └── stdout

**Comment by lukemarsden** [comment]
BTW in case this issue was unclear, when I say "outputs" I mean _all_ the files that the CLI writes in `bacalhau get` not just the output volumes.

**Comment by aronchick** [comment]
I've heard feedback that someone broke because we were writing to /tmp and then moving it to the final directory. I have fixed this to just write directly to OutputDir (unless anyone objects)

**Comment by lukemarsden** [comment]
@aronchick on the CLI side? Please link to your change. Thanks!
