### ISSUE TITLE
HTTPS URLs -u should support comma separated URLs as well as multiple -u

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#586]
Example:

```
go run . docker run \
    -u https://raw.githubusercontent.com/filecoin-project/bacalhau/main/testdata/awk_file.txt:/input/file01,https://raw.githubusercontent.com/filecoin-project/bacalhau/main/testdata/awk_file.txt:/input/file02 \
--workdir /input \
ubuntu -- ls /input
```

Got stdout:
```
file01
```

Expected:
```
file01
file02
```

Similarly, also `-u http://file.com/ -u http://anotherfile.com/` should be supported.

**Comment by lukemarsden** [comment]
The latter part might also be caused by the same root cause as #610

**Comment by NiklasTR** [comment]
I am currently working on a use-case for bacalhau for biocomputing (cc @wesfloyd). We often see multi-input functions (~ DAGs) pop up in these workflows (example from salmon below) 

<img width="865" alt="image" src="https://user-images.githubusercontent.com/18559148/191037709-83e0e1ba-94c2-42f7-a9a8-38c55b2743a6.png">

I currently have to repin files to stick to the single-input paradigm. Adding this here as I think that implementing multi-input mounting is basically the first step to solving #190 (DAGs).

## ref
https://combine-lab.github.io/salmon/getting_started/

**Comment by enricorotundo** [comment]
> I am currently working on a use-case for bacalhau in biocomputing (cc @wesfloyd). We often see multi-input functions (~ DAGs) pop up in these workflows (example from salmon below)
> ...
> I currently have to repin files to stick to the single-input paradigm. Adding this here as I think that implementing multi-input mounting is basically the first step to solving #190 (DAGs).

Hi @NiklasTR I'd be curious to learn what DAG orchestration system you usually use/prefer, if any, with your workflows. Do you have an opinion on what system you'd like to see in Bacalhau?

**Comment by NiklasTR** [comment]
Hi Enrico - we are generally interested in workflow orchestrators that are common in comp-bio, such as nextflow.

**Comment by NiklasTR** [comment]
@enricorotundo - I think a simple first step towards it is #610 ; I saw there was some recent work on it.

**Comment by enricorotundo** [comment]
Thanks @NiklasTR! Yes #610 has been shipped indeed :)
