### ISSUE TITLE
Simple Bacalhau Example/Job that moves data from a source into IPFS

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#589]
TODO

**Comment by aronchick** [comment]
Take a URL or a string of URLs, download, put them into /outputs finish.

**Comment by philwinder** [comment]
Request captured in https://docs.google.com/spreadsheets/d/1QwOAYlFOpoJbWAGs5W1KdctDUouKOwLzxgTyAhyHD6Q/edit?pli=1#gid=0
