### ISSUE TITLE
Manually tee stdout and stderr when running jobs

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#59]
We just got bitten by trying to write directly to the os.Stdout & std.Stderr streams from go-routines and this also just blocked the tests

The solution is to just return a buffer of the commands stdout & stderr and print that buffer to the console when the job has finished

It would be nice to have streaming output though - let's do this by reading the buffer from a go-routine whilst the command is running

**Comment by lukemarsden** [comment]
This isn't the solution. The workaround is that thing the Android team did.
