### ISSUE TITLE
Should we write stdout & stderr to prometheus?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#597]
```
		// TODO: Should we write stdout & stderr to prometheus?
```

https://github.com/filecoin-project/bacalhau/blob/33b2f75635d52ab87067453080c2296d520ebd19/pkg/computenode/computenode.go#L594

**Comment by lukemarsden** [comment]
No, we shouldn't, prometheus doesn't like high cardinality fields.
