### ISSUE TITLE
4. Job execution investigation: docker in firecracker

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#6]
- [x] I’m going to run the job: how does that work? Firecracker/docker
- [x] Build a prototype of firecracker/docker
- [x] Deliverable: a job can start a firecracker vm and launch an arbitrary docker container – we can run `sed`! (and we can see the result in the docker logs)

**Comment by lukemarsden** [comment]
Demo! https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1643393148899119
