### ISSUE TITLE
pipe stdin script to docker container

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#603]
Feature - ensure that this command can read stdin, and use it as an argument to docker entrypoint

Proposed solution
`cat hello.py | bacalhau docker run python -`
convert the stdin to a hex string
pass the hex string in the jobspec

convert the string back to a script and then run the script

client side

read.py script
```
words = open('names.txt','r').read().splitlines()

print(words[:10])
```

main.go or feature that can be implemented in bacalhau to convert stdin to a hex string and pass to jobspec
```
package main
import (
	"io/ioutil"
	"os"
	"fmt"
	"encoding/hex"
)

func main(){
	bytesaray, _ := ioutil.ReadAll(os.Stdin)
	encodedString := hex.EncodeToString(bytesaray)
	fmt.Println(encodedString)
}
```
Running the script outputs a hexstring, in bacalhau this would be captured in the jobspec
```
$ cat read.py | go run main.go 
776f726473203d206f70656e28276e616d65732e747874272c277227292e7265616428292e73706c69746c696e657328290a0a7072696e7428776f7264735b3a31305d29
```
server side
convert the hexstring back to a script

```
package main

import (
	"encoding/hex"
	"fmt"
)

func main() {
	a := "776f726473203d206f70656e28276e616d65732e747874272c277227292e7265616428292e73706c69746c696e657328290a0a7072696e7428776f7264735b3a31305d29"
	bs, err := hex.DecodeString(a)
	if err != nil {
		panic(err)
	}
	fmt.Println(string(bs))
}

```
This would output the decoded string
```
words = open('names.txt','r').read().splitlines()

print(words[:10])
```

after that is done we would provide the script as an entrypoint or mount the script etc. any other better methods please suggest
and this would run the script
we would also capture the name of the script somehow and save the script
this command would be an entrypoint
python read.py ?

This approach has several advantages over other ways of currently doing it
To run a script currently you have to upload it IPFS and mount the script to a container and then run it is a long process and it has multiple disadvantages like it takes lot of time to download and mount the CID for many reason, the CID isn't pinned so if a user later run it the job won't run again

advantages over python wasm
it will support all containers and custom command would work

**Comment by lukemarsden** [comment]
This is a good idea because it brings us closer to parity with `docker` CLI. It's also cool because with `--download` we could start to pipe jobs together which might be a step towards DAGs.

However, we shouldn't encode stdin in the jobspec. stdin can be arbitrarily big and we don't want unbounded size data in jobspecs on libp2p. We'd need to stream stdin to the requestor node that's receiving the API call, which needs to write it to IPFS so that it can be read by the compute nodes that run the job.
