### ISSUE TITLE
Proper Service/Storage Provider Documentation

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#607]
As a storage provider, I want simple, coherent instructions explaining how to setup bacalhau and connect it to the mainnet.

Context:
We currently have this page https://docs.bacalhau.org/running-node/overview, but it basically just explains the serve command.

Known needs:
* [ ] What hardware requirements are there?
* [ ] What OSs are supported?
* [ ] OS/Library prerequisite instructions (e.g. Docker)
* [ ] Connecting to the mainnet

Unknowns (you need to ask people about these and refine accordingly):
* Prometheus/Grafana?
* Honeycomb/tracing?
* Lotus integration (see #561)
*

**Comment by lukemarsden** [comment]
Kai: documenting whole process was only partially done. What's missed?

1. Stand up a node by following the docs at https://docs.bacalhau.org/running-node/install, find the cracks in the pavement and fix them as we go.
2. Maybe add some more context.
3. Add a systemd unit. In particular, say if you want to use systemd then here's an example?

**Comment by enricorotundo** [comment]
* Prometheus?
* Honeycomb?

**Comment by lukemarsden** [comment]
both are probably optional, although worth mentioning in the docs that they can be done!

**Comment by wesfloyd** [comment]
@enricorotundo my thoughts per the [slack discussion](https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1664808681173209?thread_ts=1664808369.068849&cid=C02RLM3JHUY) are:

- [ ] Identify our preferred onboarding path for Compute Providers (CPs) during this testing phase - i.e. which specific narrowly defined steps do we wish for them to take. Luke or Kai might be the best person to define this?
- [ ] Confirm Luke and Kai whether our CP docs section should be built as a "linear, narrowly defined beta tester onboarding process for CPs", "a catch-all for related compute node operator topics that deserve to be documented somewhere" or some combination of the two.
- [ ] Update our docs accordingly

Is that helpful?

**Comment by enricorotundo** [comment]
new WIP version http://localhost:3000/running-node/

**Comment by enricorotundo** [comment]
New page: https://docs.bacalhau.org/running-node/quick-start

https://github.com/filecoin-project/bacalhau/issues/900 should be the follow-up of this issue.
