### ISSUE TITLE
Make visible what can be done with Bacalhau (Luke talk to Phil)

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#609]
* Sharding over many machines
* Processing over 100TB dataset (don't have it locally)
* Python, Javascript, R?
* Focus on buzzy things, YOLO + Stablediffusion

**Comment by aronchick** [comment]
these are all incredibly rough guestimates - but just think about what we can show off. more ideas:

- [ ] stable diffusion
- [ ] YOLO (fix Vedant's documentation and simplify)
- [ ] Merge two datasets together in the cloud
- [ ] Augment an existing dataset (e.g. add a zipcode to an existing CSV based on long/lat)
- [ ] Merge a bunch of files into a single file (e.g. daily logs become a single log?)
- [ ] Nightly process an S3 bucket (e.g. nightly log uploads get processed)
- [ ] Mount a database and run a query (distributed?) - see David Gasquez in the #bacalhau channel
- [ ] Convert a very large file (or files) from one format to another (e.g. mp4 to .web? .tar to .zip? who knows)
- [ ] Take a single/small set of files out of a very large archive
- [ ] Filter a very large file/set of files to a smaller file/sets of files

**Comment by js-ts** [comment]
David is working on a javascript example

I've completed writting the commands and docs for this 
Python, R
Focus on buzzy things, YOLO + Stablediffusion and more
https://drive.google.com/drive/folders/1WMba3yWHJ8a2ywLb-y4oEV6frF1DBEzS

If a user wants to pass in a single script is this a better option https://github.com/filecoin-project/bacalhau/issues/603
or should they upload it IPFS and then mount the script ?

also certain features are not developed yet which can be very useful in improving the UX:
- Mutiple url https://github.com/filecoin-project/bacalhau/issues/586
- Using both -v and -u https://github.com/filecoin-project/bacalhau/issues/533
- As well as supporting mounting multiple CIDs https://github.com/filecoin-project/bacalhau/issues/603

**Comment by philwinder** [comment]
Thanks for all the ideas guys. We've captured them in a spreadsheet and will be working on them one at a time, with an issue for each one. 

https://docs.google.com/spreadsheets/d/1QwOAYlFOpoJbWAGs5W1KdctDUouKOwLzxgTyAhyHD6Q/edit?pli=1#gid=0
