### ISSUE TITLE
Have canary dashboard alert to Slack 

### ISSUE THREAD

**Issue by wdbaruni** [filecoin-project/bacalhau#613]
A new canary dashboard was created as part of #612 which is based on AWS CloudWatch metrics. These metrics are published out of the box by AWS Lambda that run the canaries and are not published inline by our canary code. It can be helpful to integrate this dashboard with our existing Prometheus dashboard to have a single place to monitor the health of our network. We have multiple options here:

1. Publish Prometheus metrics directly from our canary code. This will also allow more granular and latency breakdown metrics compared to what we have today. Though our test scenarios are already granular enough and just end to end metrics would be enough
2. Export existing CloudWatch metrics to Prometheus using tools like [cloudwatch_exporter](https://github.com/prometheus/cloudwatch_exporter)
3. Do nothing! Prometheus is our server side metrics dashboard, while the canary is more like client side metrics and an external health checker. While it will be nice to have a single place for all of our dashboards, it may not justify the effort for now. However, the moment that we realize these out of the box metrics are not enough, and that we need to publish inline metrics in our code, we should publish to Prometheus and not CloudWatch

cc: @enricorotundo

**Comment by enricorotundo** [comment]
I love #612, well done Walid! 

Would `cloudwatch_exporter` run in a cron job?

**Comment by wdbaruni** [comment]
I didn't look into yet, and it looks like there are other alternatives, such as [yet-another-cloudwatch-exporter](https://github.com/nerdswords/yet-another-cloudwatch-exporter). We can evaluate the exporting options once you decide it is a priority

**Comment by enricorotundo** [comment]
@lukemarsden WDYT ☝️ ?

**Comment by lukemarsden** [comment]
I think the only thing that matters is that Cloudwatch is configured to alert to Slack and that we publicize the link to the dashboard, e.g. as a pinned item in Slack. We can also link to it from the global Bacalhau dashboard when we put that live :-)
