### ISSUE TITLE
Render examples into docs

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#615]
Stealing this issue to track the rendering of the examples

Tasks:
* [ ] Create a pipeline on the examples repo that renders markdown and commits the result to docs repo.
* [ ] Organise examples to provide better structure in the docs
* [ ] Add hidden notes showing people how this works

**Comment by aronchick** [comment]
Love it - maybe @hamelsmu can advise 😃

qq - should we be keeping everything in a mono repo to simplify staying in sync?

**Comment by lukemarsden** [comment]
https://github.com/bacalhau-project/examples is the canonical place for examples

**Comment by lukemarsden** [comment]
We also plan to let users launch the notebooks in Colab for easy tire-kicking, even in a hackathon context etc

**Comment by enricorotundo** [comment]
@philwinder are we using jupytext? nbdev? what's the difference?
