### ISSUE TITLE
Ensure that failed jobs still have results (in particular, stdout, stderr) published

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#624]
If a container returns a non-zero exit code we currently swallow stdout,err and don't give the user any way to get it back. This a regression and makes developing on the network extremely painful. Fix it by publishing the stdout/err even for non zero exit code container executions.

We should also make the UX of a failed job hint to the user that they should get the stderr/out from `bacalhau get` and/or encourage users to use `--download` (which prints stdout/err immediately to the screen) or even make download the default?

**Comment by aronchick** [comment]
has this work started? i've been doing a bunch of refactoring in this area and am worried we're doing duplicate work

**Comment by binocarlos** [comment]
It turns out we were actually doing this - i.e. publishing a full result set even in the case of the container doing an exit >= 1

I've added a test to check for this now
