### ISSUE TITLE
Migrate video-filter-sharding demo to new format

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#630]
- [x] Migrate: https://github.com/bacalhau-project/examples/blob/main/data-engineering/video-filter-sharding/video-filter-sharding.ipynb
- [x] Elaborate description

**Comment by aronchick** [comment]
Possibly addresses this issue? https://github.com/filecoin-project/bacalhau/issues/632

**Comment by enricorotundo** [comment]
Thanks @philwinder for pushing this forward! 🔥
