### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#673]
Finish this up and land it

**Comment by simonwo** [comment]
Actual support landed in #681, but keeping this issue around until we've also done documentation as well. Documentation should include:

- How to install and run on Windows (just what to do with the exe)
- What is supported and what is not (client is supported, nodes may work, resource limits unsupported)

**Comment by simonwo** [comment]
Documentation updated in https://github.com/bacalhau-project/docs.bacalhau.org/pull/30.
