### ISSUE TITLE
[example] Pinning files workload onboarding example

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#676]
A simple workload onboarding example showing people how to push their files up to a pinning service.

Core bacalhau use:
* [x] Using the URL option to upload to IPFS
* [x] Using the resulting IPFS cid as an input for the next job

Pinning Services:
* [x] Local laptop -> web3.storage
* [ ] S3 -> web3.storage
* [x] URL -> web3.storage
* [x] URL -> Estuary

Other methods:
* [ ] Starting an IPFS damon and ipfs getting the file

**Comment by aronchick** [comment]
Small add-on (or separate issue?).

Could we build a TRIVIAL container/example that took a URL and uploaded it to IPFS/FIL/Estuary (maybe all three?)

**Comment by philwinder** [comment]
Waiting for estuary invite key...

**Comment by philwinder** [comment]
Complete. Updated docs with estuary: https://docs.bacalhau.org/examples/data-ingestion/
