### ISSUE TITLE
Figuring out how to reject sibyl attack

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#68]
Example:
1) I spin up a cluster of 10 nodes, the first is VERY fast, and the rest are very cheap.
2) I accept a job on all 10 nodes.
3) I finish the job on the first node
4) Then I fast stop the remaining nodes and return the same trace from the first node (with some fuzzing).

**Comment by lukemarsden** [comment]
I think the key here is somehow ensuring that node allocations for verification jobs are evenly distributed in the network, to make the probability that a malicious colluding network minority actually gets many of the same verification jobs. Making the verification jobs high enough value that everyone wants to do them and then having the clients do even distribution should help here (see protocol I proposed last week).

Is your example an attack on correctness or just trying to get paid for more work than you've actually done? It's not clear from the example.

If it's a correctness attack, the even distribution should mean that attackers with malicious colluding minorities get caught out and slashed often enough that it's not economically rational for them. If it's just about getting paid more, the even distribution point doesn't make that impossible, but it should make it rare enough that it doesn't win you a significant reward.

It's a good point though that encryption between the client and each server doesn't guarantee that the servers won't chatter out of band.

**Comment by aronchick** [comment]
Yeah, I agree with both of these points - my thought was more about getting paid more, but it ALSO affects correctness. E.g. if I'm able to mount a 51% attack against a job, then i could ALSO report all the jobs results are zeros, and no one could override me.

Spreading is key - I don't know if there's any research out there on how to confirm it, other than reputation and very large job repetition.

**Comment by lukemarsden** [comment]
I don't think you even strictly need reputation if the expected value of cheating is largely negative. Some unusual individual jobs might get 51%'d quite easily but think of the operation of the network in aggregate, assuming sufficient spreading, this should be able to make malicious behaviour economically irrational and therefore stop it happening.
