### ISSUE TITLE
bacalhau cat/ls JOB_ID

### ISSUE THREAD

**Issue by js-ts** [filecoin-project/bacalhau#682]
https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1664254126303019

Since downloading the results using bacalhau get or --download can be slow, and if you just have something printed to stdout, there should be only one step
just one step not two/three (bacalhau get, cat stdout)
$ ipfs cat bafybeidu4zm6w5vit27ybzakzsqzk4rqvrqjm5zil2lujpk47jqehlse4e/stdout
Hello World  

`bacalhau cat JOB_ID/stdout`
Hello World 

or 

`bacalhau cat JOB_ID/stderr`
exit code was zero

this would also include list funtionality

being able to selectively download just some files from the results would be nice, esp when there's large results and a small stdout,err file for example
`bacalhau ls JOB_ID/outputs`
file1
file2

**Comment by simonwo** [comment]
So is the plan to make `bacalhau cat outputs/file1` work?

**Comment by js-ts** [comment]
I think, yes

**Comment by lukemarsden** [comment]
* `bacalhau results ls`
* `bacalhau results get` by default with nothing gets all the results
* `bacalhau results get foo` gets file (downloads it to local dir)
* `bacalhau results cat foo` synonym for `get foo` + print it

**Comment by lukemarsden** [comment]
Let's move the existing get command under this `results` top level command - thanks!

**Comment by aronchick** [comment]
with all of the work @binocarlos did, is this still valid?
