### ISSUE TITLE
Cron as a service

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#70]
Feature request; I’d like Cron on Filecoin as a service - Since other sovereign chains don’t have the concept of a cron service, this is a generally useful thing. It is very very very simple, but trustlessly executed Cron I think is a powerful building block. For reference, a Web2 PaaS service, Render, charges $1/month for Cron Jobs https://render.com/pricing

**Comment by wesfloyd** [comment]
This is also a large and fast growing demand for this in the DeFi space where cron jobs are also referred to as "keepers" (Chainlink Keepers, Gelato, OpenZeppelin Defender Autotasks, and Cronos.so). Bacalhau would have a unique value prop for this industry given its fully decentralized approach

**Comment by wesfloyd** [comment]
Adding a note that this feature would be valuable for the [Filecoin Green REC workload](https://docs.google.com/document/d/11_cqaupPGsjzB0wq0I17NAAtF7EFqTiorPrUlAvftYs/edit?usp=sharing)

**Comment by wesfloyd** [comment]
Adding a note that this feature would be valuable for the [Gitcoin Passport](https://passport.gitcoin.co/) team

**Comment by aronchick** [comment]
We really need a design doc on this - examples of exactly what they’d like and how they’d want to run it. Eg

do they need the same job?
Will it take new env parameters?
Are outputs always the same? (Could be an issue with ipfs)
Etc

wanna start it @wesfloyd?

**Comment by aronchick** [comment]
@wesfloyd - any chance you can pull together a quick set of requirements here?

**Comment by davidgasquez** [comment]
Happy to help sharing some use cases!

**Comment by wesfloyd** [comment]
@aronchick yes, apologies for the delay on this. I spoke to Enrico a few weeks ago to see if we would get CRON for free via our Airflow implementation, but neglected to update this issue. I will start on a requirements doc either way.

@enricorotundo on a related note - do you have any visibility on whether we would get [DAG Runs (cron'ish)](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#cron-presets) via our planned Airflow+Bacalhau implementation?

**Comment by wesfloyd** [comment]
# Cron as a Service Requirements (v0)

## Background

## Requirements
1) "Ability to configure a Bacalhau job to be launched automatically once per day". 
- Although this is a much more simplified requirement than a proper/complete [crontab implementation](https://man7.org/linux/man-pages/man5/crontab.5.html), this is the minimum requirement needed for the Filecoin Green REC and Gitcoin workloads.
- Do they need the same job daily? Yes
- Will it take new env parameters? User is open to our preferred implementation
- Are outputs always the same? No. The outputs would rarely be the same

*Note: I'll update this entry after meeting with @davidgasquez next and getting his input.

**Comment by wesfloyd** [comment]
@aronchick two followup questions:
1. Do you mind if I write the requirements inline to this issue? Or do you prefer I build it in another spot? 
2. Would you like for me to limit the doc to "requirements" only or also some level of "solution design" proposal?

**Comment by enricorotundo** [comment]
> @enricorotundo on a related note - do you have any visibility on whether we would get [DAG Runs (cron'ish)](https://airflow.apache.org/docs/apache-airflow/stable/dag-run.html#cron-presets) via our planned Airflow+Bacalhau implementation?

@enricorotundo definitely yes - those cron presets are 100% supported :)

**Comment by wesfloyd** [comment]
@enricorotundo appreciate the heads up. I've moved the CRON Design Requirements to [this notion page](https://www.notion.so/pl-strflt/CRON-as-a-Service-Requirements-2e2e914ebe634deeb85bf65d400efe6e).

@enricorotundo can you share a link to our DAG design doc? I'm trying to verify whether the CRON requirements are 100% covered by our DAG/Airflow implementation (I think they are).

@aronchick can I get your feedback on whether the CRON Requirements notion page above is sufficient for our purposes?

**Comment by aronchick** [comment]
Let's have the discussion over there
