### ISSUE TITLE
[Example] Stable-Diffusion

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#715]
See https://drive.google.com/drive/u/1/folders/1WMba3yWHJ8a2ywLb-y4oEV6frF1DBEzS

**Comment by lukemarsden** [comment]
Let's do a demo where we have:

```
prompt_01.txt contains
flying cactus

prompt_02.txt contains
fish with wings
```

etc

**Comment by lukemarsden** [comment]
https://github.com/bacalhau-project/examples/tree/vedant-examples/model-inference

**Comment by lukemarsden** [comment]
use the GPU version of this please

**Comment by lukemarsden** [comment]
we also need to scale up the number of GPUs on the production network so we can demonstrate doing many diffusions in parallel (using the sharding example above). Let's say... 5?

**Comment by philwinder** [comment]
Completed in https://docs.bacalhau.org/examples/model-inference/stable-diffusion-cpu/
