### ISSUE TITLE
Can we comment out next four lines and just use runtime.Job.JobId?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#77]
```
	// TODO: Can we comment out next four lines and just use runtime.Job.JobId?
```

https://github.com/filecoin-project/bacalhau/blob/ab0aa3a1065133d19085ae7040e95df59e666f24/internal/runtime/runtime.go#L45

**Comment by aronchick** [comment]
Context: @binocarlos and I found a bunch of JobIds everywhere. Need to clean up naming - see #78

**Comment by binocarlos** [comment]
This is stale now we have refactor branch merged
