### ISSUE TITLE
[bug] `--download` flag consistently time's out, even though `--wait` and subsequent get works

### ISSUE THREAD

**Issue by philwinder** [filecoin-project/bacalhau#787]
With a reasonably sized input (I think) the `--download` flag consistently fails with a time out.

E.g. 
```
bacalhau docker run --download --inputs QmSgzNDSdkWKR8kBNLAKeaznjKUoD4NAJjgzt7248ktqxM ubuntu -- ls -l /inputs/.
```

But a wait and a get works fine:

```
bacalhau docker run --wait --inputs QmSgzNDSdkWKR8kBNLAKeaznjKUoD4NAJjgzt7248ktqxM ubuntu -- ls -l /inputs/.
bacalhau get $JOB_ID
```

This leads me to theorise that the `--download` code is using different code to the `get` code and the issue has been fixed in the get code not the other.

If this is the case, then refactor to unify the code between the get and the download flag.

**Comment by simonwo** [comment]
Hm, I just ran the example and it completed:

```
./bacalhau-v0.2.5 docker run --download --inputs QmSgzNDSdkWKR8kBNLAKeaznjKUoD4NAJjgzt7248ktqxM ubuntu -- ls -l /inputs/.
9e34bce5-278c-4dbe-8909-bd04fd844863
10:28:38.635 | INF ipfs/downloader.go:115 > Found 1 result shards, downloading to temporary folder.
10:28:41.123 | INF ipfs/downloader.go:195 > Combining shard from output volume 'outputs' to final location: '/Users/simon/bacalhau'

total 8
-rw-r--r-- 1 root root    1 Oct  4 08:10 exitCode
drwxr-xr-x 2 root root 4096 Oct  4 08:10 outputs
-rw-r--r-- 1 root root    0 Oct  4 08:10 stderr
-rw-r--r-- 1 root root    0 Oct  4 08:10 stdout
```
Can you share anything more about your setup?

They are indeed two different code paths, but they boil down to the same three calls: `APIClient.Get`, `APIClient.GetResults` and `ipfs.DownloadJob`… so not a huge amount of variation between them.

**Comment by enricorotundo** [comment]
```
bacalhau docker run \
    --inputs bafybeig63whfqyuvwqqrp5456fl4anceju24ttyycexef3k5eurg5uvrq4 \
    --download \
    ghcr.io/bacalhau-project/examples/openmm:0.1 -- ls -la /inputs/


e694102f-99eb-4982-9bc9-95a7ecadf28a


11:57:02.188 | INF ipfs/downloader.go:115 > Found 1 result shards, downloading to temporary folder.
11:57:12.192 | ERR ipfs/downloader.go:172 > Timed out while downloading result.
Error: error executing job: cmd/bacalhau/utils/ExecuteJob: error downloading results: failed to get ipfs cid 'QmPN6yBvajpP9whULgRimv9NZCsNuzJe8aPJ2Jv4EtHr3w': Post "http://127.0.0.1:5001/api/v0/files/stat?arg=%2Fipfs%2FQmPN6yBvajpP9whULgRimv9NZCsNuzJe8aPJ2Jv4EtHr3w": context deadline exceeded
```

**Comment by philwinder** [comment]
@simonwo Yeah it's not a system/setup thing, it's a load related thing. It works sometimes, not others (as enrico has shown in an independent example). E.g. I just ran it again now and it worked.

Basically if the system is quiet enough then it probably reacts within the timeout and works. But often it doesn't.

I think this is probably because the timeouts coded in the `--download` code are not the same as the timeouts in the `get` code. Or not implemented the same, or something.

**Comment by simonwo** [comment]
P.s. if this is causing much immediate grief, there is a `--download-timeout-secs` flag which you can manually set to 600.
