### ISSUE TITLE
ASSIGNMENT: All read

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#80]
https://www.microsoft.com/en-us/research/uploads/prod/2018/03/build-systems.pdf

cc @lukemarsden @wesfloyd @binocarlos

**Comment by wesfloyd** [comment]
@aronchick reading through it now. Can you share any additional context on how it would directly apply to Bacalhau? E.g. 1) user submits a compute job written in Bacalhau SDK .. 2) Bacalhau scheduler builds a dynamic build plan to assign work to compute servers ..

Also - like to throw in a personal favorite on this topic - https://tez.apache.org/ - complex directed-acyclic-graph of tasks for processing data . [Who doesn't like DAGs](https://www.youtube.com/watch?v=ZXILzUpVx7A)?

**Comment by lukemarsden** [comment]
Do you see this feeding into our DAG design work, @aronchick? Or something else?

**Comment by aronchick** [comment]
@DhashS talked about it at length - this was some of the seminal work behind that sharded gcc builder example (I believe).

The thought that I think this leads into goes a bit further than just the DAG design work - it's more "you've given me a very large tasks, we'll break it up for you". More than a little bit magical thinking, but hopeful!
