### ISSUE TITLE
Need to not os.Exit(1) (I think)

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#81]
https://github.com/filecoin-project/bacalhau/blob/otel/cmd/bacalhau/devstack.go#L71

We os.Exit(1) here, but I don't think this is correct. Interrupt is the correct thing to do, and this seems that it's an error. Regardless, by doing so, I think it's preventing us from submitting Otel traces (because the process finished).

cc @binocarlos @lukemarsden

**Comment by aronchick** [comment]
Chatted with the otel devs - we need to do something like this at the end of the world

span.End()
context.Done()
cancelFunction()
os.Exit(1)

**Comment by aronchick** [comment]
Think i've solved this (sort of).

At least now ctrl+c works - but then we don't have a good error case path. We're going to need to do some standardization here.

**Comment by lukemarsden** [comment]
Can we put the error handling in the generic command entrypoint https://github.com/filecoin-project/bacalhau/blob/main/cmd/bacalhau/root.go#L45?

**Comment by lukemarsden** [comment]
Also, not sure what you mean by "Interrupt is the correct thing to do"?

**Comment by aronchick** [comment]
> Also, not sure what you mean by "Interrupt is the correct thing to do"?

If I spin up `bacalhau devstack` then it SHOULD run forever, responding only to a -HUP. So that interrupt is "correct".

I agree that the error handling (according to go best practices) is at the "End of the World" - e.g. the generic entry point. If someone doesn't get to this during refactoring, then i can take it.

**Comment by aronchick** [comment]
Interesting in this context - https://go101.org/article/channel-closing.html

**Comment by lukemarsden** [comment]
But a signal is something the process receives and acts on for example by
cleaning up and exiting with a certain exit code. I don't see the issue
with exiting with exit code 1 in the case of an unrecoverable error.

**Comment by lukemarsden** [comment]
That said I just looked at the code now at
https://github.com/filecoin-project/bacalhau/blob/otel/cmd/bacalhau/devstack.go#L71
and it looks fine to me

**Comment by aronchick** [comment]
Correct - but I think we have os.Exit(1) where we're just trying to do loop termination? If not, we can close

**Comment by lukemarsden** [comment]
Ah! So there's a valid exit(1) in the main entry point and then some other
random ones scattered around the code? In that case I agree we should get
rid of the latter!
