### ISSUE TITLE
Test suite improvements

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#812]
ETA: 2023Q1

I'm constantly writing code that goes something like this:

 * setup some kind of stack (devstack with IPFS + docker OR noop)
 * submit some kind of job
 * wait for the job to complete (and error if not)
 * get the results of the job
 * assert something in the results

I am probably guilty of copy pasta at least 10 times with tests that do basically the same flow as above

So - the "refactor the tests" pass#1 might involve three main things:

 * get the noop stack to record events and generally behave as much like docker + ipfs as possible but without the hard dependencies
   * #600
   * #598
 * replace all the tests that don't actually need IPFS and Docker with the above - more realistic noop stack
 * refactor all the tests that basically have the same flow as above into a function with hooks that will hopefully reduce a lot of the boilerplate, copied code
 * Please experiment with turning off WIFI for a day, and make tests work :) https://github.com/filecoin-project/bacalhau/issues/635 - https://github.com/filecoin-project/bacalhau/issues/277

**Comment by simonwo** [comment]
+1 for making more use of the Noop stack, which increases the surface area testable on Windows CI...

**Comment by binocarlos** [comment]
related: #471

**Comment by simonwo** [comment]
I think with the Scenario tests we now have this.
