### ISSUE TITLE
Please update the public server

### ISSUE THREAD

**Issue by dylancaponi** [filecoin-project/bacalhau#826]
[When following the hello world docs](https://docs.bacalhau.org/getting-started/installation/#submit-a-hello-world-job), I'm getting:
`client version v0.2.7 is newer than server version v0.2.6, please ask your network administrator to update Bacalhau`

**Comment by aronchick** [comment]
@enricorotundo @philwinder @wdbaruni @binocarlos @lukemarsden 

This is production down, for better or worse.
Please try to get to this asap.

**Comment by enricorotundo** [comment]
We're on `v0.3.1` now and client/server have been aligned 🎉  Thanks @dylancaponi for reporting this one.
Kudos to whoever fixed this 😁

**Comment by scenaristeur** [comment]
same for me on, windows today 

```
Client Version: v0.3.17
Server Version: v0.3.16

C:\Users\MSI SLI\Console2>bacalhau docker run ubuntu echo Hello World
client version v0.3.17 is newer than server version v0.3.16, please ask your network administrator to update Bacalhau
Error: client version v0.3.17 is newer than server version v0.3.16, please ask your network administrator to update Bacalhau
```

**Comment by wdbaruni** [comment]
Thanks for reporting this. v0.3.17 is in pre-release state and shouldn't be picked up by the install script. I tried on my mac and it also pulled v0.3.17 instead of v0.3.16 (latest)

**Comment by wdbaruni** [comment]
Correction. The install script pulled the correct v0.3.16. Is this a Windows issue only?

**Comment by wdbaruni** [comment]
Do you mind sharing the output of `curl -sL https://get.bacalhau.org/install.sh | bash`?

**Comment by scenaristeur** [comment]
I've just downloaded windows tar'gz from https://github.com/filecoin-project/bacalhau/releases/tag/v0.3.16

**Comment by wdbaruni** [comment]
I see. Is it possible that you downloaded from https://github.com/filecoin-project/bacalhau/releases/tag/v0.3.17 instead of https://github.com/filecoin-project/bacalhau/releases/tag/v0.3.16?

**Comment by scenaristeur** [comment]
@wdbaruni yes, from latest as sais here https://docs.bacalhau.org/getting-started/installation/
i'll download 0.3.16 thxs

**Comment by scenaristeur** [comment]
sounds better 

```
D:\>bacalhau version
Client Version: v0.3.16
Server Version: v0.3.16

D:\>bacalhau docker run ubuntu echo Hello World
Job successfully submitted. Job ID: 6b3b52ce-8ac7-4dda-96d5-0092e8e81c37
Checking job status... (Enter Ctrl+C to exit at any time, your job will continue running):

               Creating job for submission ... done ✅
               Finding node(s) for the job ... done ✅
                     Node accepted the job ... done ✅
           Job finished, verifying results ... done ✅
              Results accepted, publishing ... Job Results By Node:

To download the results, execute:
  bacalhau get 6b3b52ce-8ac7-4dda-96d5-0092e8e81c37

To get more details about the run, execute:
  bacalhau describe 6b3b52ce-8ac7-4dda-96d5-0092e8e81c37
```

thxs

**Comment by wdbaruni** [comment]
Yeah I see the problem in the docs where it points to the releases page instead of the latest release. A pre-release will be at the top of the list and can cause a confusion. Will fix the docs, and thanks for reporting it

**Comment by scenaristeur** [comment]
thxs i cannot close this issue, you can
