### ISSUE TITLE
System transparency?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#84]
I wonder if something like this - https://www.system-transparency.org/ - could be used to increase user trust in the executions

**Comment by wesfloyd** [comment]
Big fan of these types of solutions. Whereas cloud compute frameworks only allow for 100% trust, these types of solutions allow for much more granularity and unbundling of trust. E.g. a range from "very little trust" (and low cost) to "high trust" (and higher price premium).

If we can build the trust mechanism to be modular/pluggable, then System-Transparency could be one useful approach among many.

**Comment by lukemarsden** [comment]
This seems to be a system for securing the bootloader on a physical server. How would you see it relating to our userland software?

**Comment by aronchick** [comment]
We could detect it (and/or suggest our Storage Providers build systems with it in).
