### ISSUE TITLE
Need to do truncation on all fields

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#840]
Inbound fields could result in a DOS - e.g. if i have an entry point that's 1GB

**Comment by simonwo** [comment]
We already limit inbound JSON to 10Mb, so closing.

https://github.com/filecoin-project/bacalhau/blob/5684b986af93046e8d26eb47ed4c385e40cba61b/pkg/model/utils.go#L17

If I've missed the point please reopen with more info.
