### ISSUE TITLE
Container doesn't terminate

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#86]
Getting a bunch of irregular errors - 1 that ipfs daemon can't mount 

Second that this container 
```
binocarlos/bacalhau-ignite-image:v1   "bash -c 'tail -f /d…"
```

Doesn't quit. 

We should try to clean this up better (makes developing/testing much hardor)

**Comment by lukemarsden** [comment]
Do you have a reliable way to repro this?

**Comment by aronchick** [comment]
i mean, just run the tests about 20 times and run `docker ps` and they're all there.

 `LOG_LEVEL=debug go test -run ^TestDevStack$ github.com/filecoin-project/bacalhau/cmd/bacalhau/`

![CleanShot 2022-04-19 at 11 30 27](https://user-images.githubusercontent.com/51317/164071640-7d600a72-6857-4669-afdf-19438696cfa9.png)


As far as the "ipfs daemon can't mount", i don't :( SUPER irregular.

**Comment by binocarlos** [comment]
Shutdown handling based on cancel context is now omnipresent - the docker executor for example will terminate all containers on shutdown.

The problem above was happening because we were not proactively terminating ignite vms (and each ignite vm comes with a sidecar docker container)
