### ISSUE TITLE
Job submission failure with devstack and docker: "Error connecting host ipfs into container"

### ISSUE THREAD

**Issue by wesfloyd** [filecoin-project/bacalhau#87]
To reproduce:
Follow instructions in [devstack.md](https://github.com/filecoin-project/bacalhau/blob/main/docs/devstack.md) to 1) bring up devstack cluster, 2) submit file and 3) submit the job

Expected result:
Job will be in running or complete status

Actual result:
Job is in "error" state with "failed to dial" error. Full logs attached.

// Please let me know if you'd like more detail in the errors opened in the future

Server displays the following error (full logs attached):
[2207] ERR internal/compute_node.go:95 > ERROR running the job: Error connecting host ipfs into container:
        Error: exit status 1
        Output: Error: connect 12D3KooWKVEB1vfxoW2ovnu2PnYjgSaR2AYYzhqgjRkx65AA4rQC failure: failed to dial 12D3KooWKVEB1vfxoW2ovnu2PnYjgSaR2AYYzhqgjRkx65AA4rQC:
  * [/ip4/172.17.0.2/tcp/4001] dial tcp4 172.17.0.2:4001: connect: connection refused

[IPFS connection error.txt](https://github.com/filecoin-project/bacalhau/files/8512795/IPFS.connection.error.txt)
[IPFS Error Client Submission.txt](https://github.com/filecoin-project/bacalhau/files/8512796/IPFS.Error.Client.Submission.txt)

**Comment by wesfloyd** [comment]
Adding screenshots:
<img width="1352" alt="client view" src="https://user-images.githubusercontent.com/260568/164510562-8cf950d9-1b7e-4a83-b255-64cbd8f45b44.png">
<img width="1352" alt="server" src="https://user-images.githubusercontent.com/260568/164510568-0c05bed4-bdad-4668-b1ef-bca34a0022ef.png">

**Comment by binocarlos** [comment]
This should be fixed now we are using the api copy driver by default
