### ISSUE TITLE
Design doc for UX philosophy

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#886]
So we have clearer alignment on future UX changes, let's write up our principles

**Comment by lukemarsden** [comment]
came across this, which already captures a lot of what's in my head:
https://docs.google.com/document/d/1PElwrngdbmlktqFI8Ukl5Qnk4kS2YF5jcy3RkGbZkL4/edit#
cc @aronchick

**Comment by aronchick** [comment]
@fakela can we turn this into a notion doc?

**Comment by fakela** [comment]
Done https://pl-strflt.notion.site/Bacalhau-CLI-799c479c09d641a1adad25bfdd575384
