### ISSUE TITLE
On new machine, trying to run `bacalhau list` gives an error on close

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#898]
as root:
`bacalhau list -n 100 --output foo.json`

See:
```
00:59:51.975 | FTL system/cleanup.go:68 > could not create memory profile: open /tmp/bacalhau-devstack-mem.prof: permission denied
```

**Comment by lukemarsden** [comment]
what OS?

**Comment by lukemarsden** [comment]
we should just not fail if we can't write the profile

**Comment by wjam** [comment]
Raised #933 to implement a better longer-term solution, but will stop the command now from failing with #931

**Comment by wjam** [comment]
Notes for the future:
* The output file has a hardcoded name, so multiple users on the same machine will write to the same file. This would probably cause various permission issues if the file is owned by someone else.
* [Some Linux distributions ban `root` from writing to `/tmp`](https://askubuntu.com/questions/1250974/user-root-cant-write-to-file-in-tmp-owned-by-someone-else-in-20-04-but-can-in)
