### ISSUE TITLE
Install Bacalhau on OVH bare metal

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#906]
Install Bacalhau after #802 has been completed.

**Comment by wdbaruni** [comment]
I am evaluating the need to create a Bacalhau docker image to simplify launching new nodes. I understand that spinning a production Bacalhau node is not only about running the binary as other dependencies must be installed and configured. What are your thoughts about using docker? How much effort would it have saved you?

**Comment by wdbaruni** [comment]
I am evaluating the need to create a Bacalhau docker image to simplify launching new nodes. I understand that spinning a production Bacalhau node is not only about running the binary as other dependencies must be installed and configured. What are your thoughts about using docker? How much effort would it have saved you?

**Comment by enricorotundo** [comment]
@wdbaruni I now see a compelling need to draw a line between:

1. the PL-managed network: which is bacalhau + ipfs + a number of extra facilities (e.g. tracing, logs collection, Prometheus, env vars, etc) 
2. the "basic" deployment intended for CPs: should be a one-liner -> https://github.com/filecoin-project/bacalhau/issues/900

The deployment on OVH metal pertains to (1). I had a go in writing [an awful ssh-installer script in this branch](https://github.com/filecoin-project/bacalhau/blob/620-install-instructionsscript-for-bare-metal-ubuntu/ops/scripted_install/full_install.sh) but that's a tough terrain to script because of the dependencies in (1). The problem with dockerizing that part is that we'd have to keep it in sync with terraform main.tf, right?

For (2) use-case a Docker/docker-compose node launcher would be quite helpful. Why? Because as you said you need other dependencies as well as operating the `bacalhau serve` command (e.g. install systemd service, make sure it's running, etc). Plus, those deps depend on the host OS (who knows what's the systemd equivalent in Windows10?! 🤷 ). So yeah re: (2) I see a strong case for docker!

Btw, re: Docker - we just received this PR by @SvenDowideit 😃  https://github.com/filecoin-project/bacalhau/pull/1364, see related 🧵 https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1669280791045329

**Comment by enricorotundo** [comment]
Oh. There's also a 3rd use case, as @SvenDowideit pointed out, before really joining as a CP you may just want to try things out. Locally.

**Comment by wdbaruni** [comment]
There will be two types of CPs:
1. A simple user who wants to participate in the network with their laptop or old computer. For those, the onboarding should be as simple as possible (e.g one-line command, Station desktop app, ...), and they don't care much about traceability or log collection
2. Service providers who have invested hardware in the network who they want to be heavily utilized, and aim at maintaining high availability and reputation to earn more rewards and avoid getting slashed. These service providers do care about traceability, metrics, logging, ... and all other ops aspects that we care about in our current network. I am hoping to avoid re-inventing the wheel and have each of these service providers build their own solutions from scratch to operate Bacalhau at a production level. They are free to do things differently, but we should set a golden standard and reduce the onboarding barrier
