### ISSUE TITLE
Release v0.3.4 and re-enable Estuary on mainnet

### ISSUE THREAD

**Issue by simonwo** [filecoin-project/bacalhau#908]
We'd like Estuary integration to be back online before Lab Week. We will need to release the Estuary resilience changes and put the API Key back into the environment.

As discussed: https://filecoinproject.slack.com/archives/C02RLM3JHUY/p1666024774081589

**Comment by philwinder** [comment]
We've released `v0.3.4` now, if the fix was specifically in that version...
