### ISSUE TITLE
CLI progress steps feel one step behind

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#914]
The progressive display on the CLI (which is my favorite thing ever) sometimes feels like it's behind

![image](https://user-images.githubusercontent.com/1676629/196745757-5ccac523-0d68-4ed5-b841-1d594eccf003.png)

The above image is me submitting 3 GPU jobs to the network when it has 2 GPUs

So - the third job is waiting - that is what I would expect

Here are two UX issues from the output in the screenshot above:

### running status

The running jobs look like they are still waiting to be "accepted" by the nodes because they say `Node accepted the job ...`
Perhaps that should say `Node running the job ...`

### waiting to be allocated status

The bottom job has been created and submitted - I would expect a tick next to `Creating job for submission` to appear right away

I would expect it to be blocked on `Finding node(s) for the job` (because the other two nodes are busy running their jobs so that would make sense)

The above two things are probably tiny text changes but would make a massive improvement to the UX when using it

**Comment by binocarlos** [comment]
Ahhh so I see this code:

```
model.JobEventBidAccepted: {Message: "Node accepted the job", IsTerminal: false},

// Job is on ComputeNode
model.JobEventRunning: {Message: "Node started running the job", IsTerminal: false},
```

which clearly is making a dinstinction between `JobEventBidAccepted` and `JobEventRunning` - in which case I think perhaps we are not getting a `JobEventRunning` event

**Comment by philwinder** [comment]
Yeah I've definitely seen the job stuck at the node selection stage, with no green tick, even though I know the job is already running.

Run a long gpu job (e.g. gpu stable diffusion) to recreate this.
