### ISSUE TITLE
Can I use Bacalhau for data sharing? 

### ISSUE THREAD

**Issue by Rashmi-278** [filecoin-project/bacalhau#936]
I wanted to upload and archive data on filecoin, with it I wanted to be able to share the IPFS data easily, Can I do that with Bacalhau? If yes, can you please guide me on How to ?

**Comment by aronchick** [comment]
Sure thing! Can you say more what you'd like to do? 

Here's docs on uploading a file via bacalhau - 
```
https://docs.bacalhau.org/examples/data-ingestion/
```

It's a bit out of date though, ALL content uploaded goes to estuary by default.

**Comment by Rashmi-278** [comment]
Thank you ! We plan to Archive Neuroscience datasets, You might have heard about us from Shady El Damaty, Opscientia
