### ISSUE TITLE
integrate otel in refactor branch

### ISSUE THREAD

**Issue by binocarlos** [filecoin-project/bacalhau#97]
We need a tracing library for otel integrated with each stage of a job flow - so when we run stress tests we can identify bottlenecks and see what is happening with the system overall.

The tracing code in the [v0.1 branch](https://github.com/filecoin-project/bacalhau/tree/v0.1) can be used as a reference or we can use another tracing library.

To capture each stage of a job's lifecycle - we will need captures in each of the following places:

 * the CLI
 * JSONRpc server (see note below)
 * transport
 * requestor node
 * compute node
 * executor
 * storage provider (for prepare storage hook)
 
 **JSONRpc server**
 
 There are currently issues with integrating otel with the standard go JSON rpc server that we use (it seems very hard to pass the trace id through the JSON rpc server)
 
 We will probably need to replace the JSONRpc server to use https://github.com/gorilla/rpc or something else
 
  **HoneyComb**
  
In the v0.1 branch - there is an integration with the honeycomb service so we visualise the tracing data we collect.

We should keep this integration and make it easy to configure different api keys

**Comment by binocarlos** [comment]
Possibly what we should do is replace the JSONRpc api with a standard REST api because:

 * it is what ipfs uses
 * it would make plugging in otel handlers easier

**Comment by Bubblyworld** [comment]
Also to record something me and kai talked about on hangouts - I think it makes sense to pass a `context.Context` as the first parameter of all of the operational functions in the codebase. Gives us a convenient place to store request-scoped and run-scoped data, like:
* timeouts, for short-lived requests
* cancellations, for handling interrupts for instance
* trace IDs and other telemetry

**Comment by aronchick** [comment]
cc @enricorotundo i think you're working on this?
