### ISSUE TITLE
Write tests for & consider edge cases for bid timeouts

### ISSUE THREAD

**Issue by lukemarsden** [filecoin-project/bacalhau#971]
https://github.com/filecoin-project/bacalhau/pull/970/files was expedient ahead of Lisbon as we were observing GPU leases getting clogged up and never emptied.

One consideration is that with `--min-bids`, might 60 seconds not be long enough for nodes to bid? Probably not, bidding is a pretty instantaneous operation. But might failing shards cause jobs to get stuck somehow? More thought required. Also, test coverage needed.

**Comment by wdbaruni** [comment]
covered in https://github.com/filecoin-project/bacalhau/pull/1061
